(function(){
'use strict';
const $=s=>document.querySelector(s),S=Slipline,C=S.C,gameEl=$('#game'),canvas=$('#arena'),ctx=canvas.getContext('2d'),stage=$('#stage'),overlay=$('#overlay'),panel=$('#panel');
const defaults={ease:false,toggle:false,reduce:false,master:.65,sfx:.75,music:.18,record:false,instant_delivery:false,reduced_juice:false,keys:{up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',grip:'Space',focus:'ShiftLeft',pause:'Escape',retry:'KeyR'},pad:{grip:0,focus:4,pause:9}};
function load(){try{const v=JSON.parse(localStorage.getItem('slipline1911.settings')||'null');if(!v||typeof v!=='object')return structuredClone(defaults);const r={...defaults,...v,keys:{...defaults.keys,...v.keys},pad:{...defaults.pad,...v.pad},record:false,instant_delivery:false,reduced_juice:false};for(const k of ['ease','toggle','reduce'])r[k]=r[k]===true;for(const k of ['master','sfx','music'])r[k]=Number.isFinite(r[k])?S.clamp(r[k],0,1):defaults[k];if(new Set(Object.values(r.keys)).size!==8)r.keys={...defaults.keys};return r;}catch{return structuredClone(defaults);}}
let settings=load(),seed=101,g=new S.Game(seed),screen='home',previousScreen='home',physical=new Set(),moves=new Set(),touch={x:0,y:0,grip:false,focus:false},virtualGrip=false,startGate=false,releaseSeen=true,lastFrame=0,accumulator=0,countEnd=0,resultAt=0,resultReleased=false,remapping=null,padPrev=[],padConnected=false,debugCores=false,debugInvalid=false,readPaused=false,sessionStart=performance.now(),sessionId='',records=[],inputs=[],summaries=[],sawFirstInput=false,lastPauseReason='',pendingHoldRetry=false,stickPointer=null,stickCenter=null,scale=1,lastMode='',lastHint='',lastWire='',lastGripMarkup='',lastKeyMarkup='',activePad=null,storageNotice='';
function save(){try{localStorage.setItem('slipline1911.settings',JSON.stringify({...settings,record:false,instant_delivery:false,reduced_juice:false}));}catch{storageNotice='本地存储不可用；仍可试玩。';}}
function best(){try{const v=JSON.parse(localStorage.getItem('slipline1911.bests')||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}catch{return {};}}
function storeBest(){if(!g.result?.valid||debugInvalid)return;const all=best(),key=g.groupKey();const old=all[key];if(!old||g.score>old.score){all[key]={score:g.score,D:g.D,C:g.completed,time:g.time,hp:g.hp};try{localStorage.setItem('slipline1911.bests',JSON.stringify(all));}catch{storageNotice='成绩未能保存；仍可重玩。';}}}
function mode(){return g.options.practice?'练习 · 不计成绩':g.options.instant_delivery||g.options.reduced_juice||debugInvalid?'TEST · 成绩无效':g.options.ease?'舒缓 · 弹速80%':'标准';}
function meta(){return {participant_id:'anonymous',session_id:sessionId,build_hash:SLIPLINE_BUILD.build_hash,config_hash:SLIPLINE_BUILD.config_hash,seed:g.seed.id,mode:mode(),input_device:touch.x||touch.y||touch.grip?'touch':activePad?'gamepad':'keyboard',wall_time_ms:Math.max(0,Math.round(performance.now()-sessionStart))};}
function recordEvent(e){if(settings.record)records.push({...meta(),...e});}
function setupSink(){g.eventSink=e=>{recordEvent(e);if(e.event==='grip_release'&&e.cause!=='release'&&settings.toggle){virtualGrip=false;touch.grip=false;}if(e.event==='result'&&settings.record)summaries.push({...meta(),...g.result});};}
function unlock(){sound.unlock();}
const sound={context:null,voices:[],last:{},musicLast:0,muted:false,unlock(){try{if(!this.context)this.context=new (window.AudioContext||window.webkitAudioContext)();this.context.resume();}catch{}},stop(){for(const v of this.voices){try{v.osc.stop();}catch{}}this.voices=[];this.last={};this.musicLast=0;},tone(f,d=.08,type='sine',priority=1,amp=.1,end=f,bus='sfx'){const a=this.context;if(!a||a.state!=='running'||this.muted||settings.master===0||settings[bus]===0)return;const now=a.currentTime;this.voices=this.voices.filter(v=>v.end>now);if(this.voices.length>=C.feedback.audio_polyphony_max){const low=this.voices.reduce((x,y)=>x.priority<y.priority?x:y);if(low.priority>priority)return;try{low.osc.stop();}catch{}this.voices=this.voices.filter(v=>v!==low);}const osc=a.createOscillator(),gain=a.createGain();osc.type=type;osc.frequency.setValueAtTime(f,now);osc.frequency.exponentialRampToValueAtTime(Math.max(20,end),now+d);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,amp*settings.master*settings[bus]),now+.006);gain.gain.exponentialRampToValueAtTime(.0001,now+d);osc.connect(gain).connect(a.destination);osc.start();osc.stop(now+d+.01);this.voices.push({osc,end:now+d+.01,priority});},play(fx){const t=g.time,kind=fx.kind,min=kind==='capture'?.05:kind==='deliver'?.06:0;if(min&&t-(this.last[kind]??-1)<min)return;this.last[kind]=t;if(kind==='attach')this.tone(500,.07,'triangle',2,.14,850);if(kind==='capture')this.tone(850,.04,'sine',1,.09,1150);if(kind==='deliver')this.tone(620+Math.floor((fx.level||0)/6)*80,.075,'sine',2,.11,800);if(kind==='cut')this.tone(350,.1,'triangle',2,.08,180);if(kind==='needle')this.tone(1700,.12,'square',5,.04,1250);if(kind==='hit')this.tone(110,.18,'sawtooth',6,.12,55);if(kind==='complete'){this.tone(523,.35,'triangle',4,.11,660);this.tone(659,.32,'sine',4,.06);this.tone(784,.28,'sine',4,.05);}if(kind==='clear'){this.tone(523,.6,'sine',4,.09);this.tone(784,.55,'sine',4,.07);}if(kind==='result')this.tone(220,.2,'triangle',3,.08,130);},ambient(){if(!this.context||settings.reduced_juice||screen!=='run'||g.time-this.musicLast<3)return;this.musicLast=g.time;this.tone([130.81,146.83,164.81,146.83][Math.floor(g.time/3)%4],.8,'sine',0,.035,130.81,'music');if(g.beads.length)this.tone(280,.15,'sine',0,.025,390);}};
let playedFx=new Set(),bodyStretch=1,bodyAngle=0,lastDrawTime=performance.now();
function uiFocus(){gameEl.focus({preventScroll:true});}
function cancelInputs(preserveGrip=false){moves.clear();touch.x=touch.y=touch.focus=0;touch.grip=false;stickPointer=null;$('#stickKnob').style.transform='';if(!preserveGrip)physical.clear();if(!settings.toggle)virtualGrip=false;startGate=false;accumulator=0;}
function start(practice=false,newSeed=seed){unlock();sound.stop();sound.muted=false;const held=new Set(physical);cancelInputs();physical=held;virtualGrip=false;seed=newSeed;g=new S.Game(practice?101:seed,{ease:settings.ease,instant_delivery:settings.instant_delivery,reduced_juice:settings.reduced_juice,practice});g.armed=true;sessionStart=performance.now();sessionId='local-'+Date.now().toString(36);setupSink();recordEvent(g.events[0]);screen='run';startGate=true;releaseSeen=false;resultReleased=false;debugInvalid=false;debugCores=false;pendingHoldRetry=false;bodyStretch=1;bodyAngle=0;playedFx=new Set();sawFirstInput=false;lastFrame=performance.now();overlay.hidden=true;uiFocus();update();}
function pause(reason='已暂停'){if(screen!=='run'&&screen!=='countdown')return;screen='pause';lastPauseReason=reason;releaseSeen=g.armed;cancelInputs(true);sound.muted=true;g.emit('pause',{cause:reason});showPause();}
function showPause(){screen='pause';sound.muted=true;overlay.hidden=false;panel.innerHTML=`<div class="eyebrow">暂时停在这里</div><h2>${g.options.practice?'练习已暂停':'已暂停'}</h2><p>${escapeHTML(lastPauseReason||'所有弹幕、珠和时间都已冻结。')}</p><p class="sub">继续前有一秒倒数。${settings.toggle?'点按接线状态保持。':'按住接线可保留货物，松开则割线。'}</p><div class="actions"><button class="primary" data-act="resume">继续</button><button data-act="settings">设置</button><button data-act="help">查看玩法</button><button data-act="practice">重看练习</button>${g.options.practice?'<button data-act="formal">跳过练习，开始正式局</button>':''}<button class="danger" data-act="abandon">结束这一局</button></div>`;focusPrimary();update();}
function resume(){unlock();screen='countdown';countEnd=performance.now()+1000;accumulator=0;panel.innerHTML='<div class="countdown"><div class="eyebrow">准备继续</div><h1 id="countNumber">1</h1><p>按住接线保留货物，松开则割线。</p><div class="actions"><button data-act="cancelcount">取消倒数</button></div></div>';focusPrimary();}
function finishUI(){if(screen==='result')return;screen='result';resultAt=performance.now();resultReleased=false;cancelInputs(true);sound.muted=false;storeBest();overlay.hidden=false;const r=g.result,b=best()[g.groupKey()],title=r.cause==='CLEAR'?'六港已送满':r.cause==='FAILED_HIT'?'身体被击中了':r.cause==='FAILED_TIME'?'时间到了':r.cause==='ABANDON'?'这一局已中止':'本局测试失效';panel.innerHTML=`<div class="eyebrow">${mode()}</div><h2>${title}</h2><p>${escapeHTML(r.notes)}</p><div class="facts"><div><span>完成港口</span><b>${r.C} / 6</b></div><div><span>实际交付</span><b>${r.D} 颗</b></div><div><span>丢失在途珠</span><b>${r.lost} 颗</b></div><div><span>用时</span><b>${r.time.toFixed(1)} 秒</b></div><div><span>剩余生命</span><b>${r.hp}</b></div><div><span>得分</span><b>${r.valid&&!debugInvalid?r.score:'无效'}</b></div></div><p class="sub">${r.valid&&!debugInvalid?'同局最佳 '+(b?.score??r.score)+' 分':'练习 / TEST 不保存正式成绩'}${storageNotice?' · '+storageNotice:''}</p><div class="actions"><button class="primary" data-act="retry" disabled>重玩这一局</button><button data-act="next" disabled>换下一局</button><button data-act="home">返回开始</button>${g.lastHit?'<button data-act="death">查看死因</button>':''}</div>`;update();}
function showHome(){screen='home';sound.muted=true;cancelInputs(true);overlay.hidden=false;panel.innerHTML=`<div class="eyebrow">连接 · 收流 · 换港</div><h1>借流 <span style="font-size:14px;letter-spacing:2px;color:#67d9d0">SLIPLINE</span></h1><p>在亮起的港口按住接线，向右拉开，让圆弹碰线。<br>珠送到港才算；180秒内送满六港。</p><div class="legend"><span class="round">○ 圆弹能接</span><span class="needle">◆ 菱针穿线</span></div><div class="actions"><button class="primary" data-act="practice">先练一次</button><button data-act="start">直接开始</button><button data-act="settings">设置</button><button data-act="nextHome">换一个局面</button></div><p class="sub">局面 ${seed-100} / 4 · ${settings.ease?'舒缓弹速':'标准弹速'} · ${keyLabel(settings.keys.grip)}接线，方向键移动</p>`;focusPrimary();update();}
function focusPrimary(){if(window.scrollY>8||readPaused)return;requestAnimationFrame(()=>{if(window.scrollY>8||readPaused)return;const b=panel.querySelector('button.primary:not(:disabled)')||panel.querySelector('button:not(:disabled)');b?.focus({preventScroll:true});});}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function keyLabel(code){return {Space:'空格',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',ShiftLeft:'左 Shift',ShiftRight:'右 Shift',Escape:'Esc'}[code]||code.replace(/^Key|^Digit/,'');}
function showSettings(){previousScreen=screen==='settings'?previousScreen:screen;screen='settings';overlay.hidden=false;panel.innerHTML=`<div class="settings-head"><h2>设置</h2><button data-act="back">返回</button></div><p class="sub">弹速和实验设置从下一局生效；其余立即生效。</p><label class="field">舒缓弹速 · 成绩单列<input type="checkbox" data-setting="ease" ${settings.ease?'checked':''}></label><label class="field">点按接线，再点割线<input type="checkbox" data-setting="toggle" ${settings.toggle?'checked':''}></label><label class="field">减弱动效 / 关闭镜头轻震<input type="checkbox" data-setting="reduce" ${settings.reduce?'checked':''}></label>${['master','sfx','music'].map((k,i)=>`<label class="field">${['总音量','音效','音乐'][i]}<input aria-label="${['总音量','音效','音乐'][i]}" type="range" min="0" max="1" step=".05" data-setting="${k}" value="${settings[k]}"></label>`).join('')}<h3>改键</h3><p class="sub">点击动作，再按新键。方向键始终可移动；Esc 始终可返回。</p><div class="mapping">${Object.entries(settings.keys).map(([k,v])=>`<button data-remap="${k}">${{up:'上',down:'下',left:'左',right:'右',grip:'接线',focus:'专注',pause:'暂停',retry:'重玩'}[k]} · ${keyLabel(v)}</button>`).join('')}</div><div class="notice" id="remapNotice">${storageNotice}</div><button data-act="resetkeys">恢复默认按键</button><h3>手柄</h3><p class="sub">左摇杆移动，方向键选菜单；南键确认。菜单确认不切换握持。</p>${Object.entries(settings.pad).map(([k,v])=>`<label class="field">${{grip:'握持',focus:'专注',pause:'暂停'}[k]}<select data-pad="${k}" aria-label="手柄${k}">${[[0,'南键'],[1,'东键'],[2,'西键'],[3,'北键'],[4,'左肩'],[5,'右肩'],[8,'选择'],[9,'菜单']].map(([i,t])=>`<option value="${i}" ${v===i?'selected':''}>${t}</option>`).join('')}</select></label>`).join('')}<h3>本地试玩记录</h3><label class="field">允许记录本局输入和事件<input type="checkbox" data-setting="record" ${settings.record?'checked':''}></label><p class="sub">默认关闭。开启后只保存在内存，可下载匿名 JSONL / CSV；输入单独下载用于同构建重放，不上传。关闭即停止记录。主观感受由你填写，不自动判断。</p><div class="actions"><button data-act="export">下载事件 JSONL</button><button data-act="csv">下载结局 CSV</button><button data-act="inputs">下载输入 / 重放</button><button data-act="erase">清空本次记录</button></div><h3>开发实验 · TEST</h3><label class="field">捕获即到账<input type="checkbox" data-setting="instant_delivery" ${settings.instant_delivery?'checked':''}></label><label class="field">减少粒子和音乐修饰<input type="checkbox" data-setting="reduced_juice" ${settings.reduced_juice?'checked':''}></label><p class="sub">实验局标 TEST，成绩无效。恢复两个开关后，下一局回到正式规则。</p><button data-act="debug">调试 / 规则测试</button>`;focusPrimary();}
function showDebug(){screen='debug';panel.innerHTML=`<div class="settings-head"><h2>调试 · TEST</h2><button data-act="backsettings">返回</button></div><p class="sub">进入步进或显示碰撞核会使本局成绩无效。规则测试使用独立场景。</p><div class="actions"><button data-act="cores">${debugCores?'关闭':'显示'}碰撞核</button><button data-act="step">推进一个输入 tick</button><button data-act="selftest">运行几何自检</button></div><pre class="debug" id="debugOut">${escapeHTML(JSON.stringify({seed:g.seed.id,step:g.steps,config:SLIPLINE_BUILD.config_hash,objects:[g.hazards.length,g.beads.length],maxObjects:[g.maxHazards,g.maxBeads],grip:g.wire,armed:g.armed,hazards:g.hazards.slice(0,24).map(b=>({id:b.id,type:b.type,x:b.x,y:b.y,vx:b.vx,vy:b.vy})),beads:g.beads.map(b=>({id:b.id,u:b.u,port:b.port_id})),lastHit:g.lastHit,warning:g.warnings.map(w=>({type:w.type,k:w.k,speed:w.speed})),events:g.events.slice(-8)},null,2))}</pre><h3>人工观察</h3><p class="sub">仅记录观察者自己确认的内容。需先开启本地记录。</p><label class="field">事件<select id="observerEvent"><option value="confusion">困惑</option><option value="self_report_fun">本人说有趣</option><option value="self_report_boredom">本人说重复</option><option value="self_report_frustration">本人说受挫</option><option value="spontaneous_technique">自发技巧</option><option value="voluntary_offer">提供自由选择</option><option value="instructed_task">指派任务</option></select></label><label class="field">原话 / 观察<input type="text" id="observerNote" maxlength="240"></label><button data-act="observe">保存本地观察</button>`;focusPrimary();}
function backSettings(){remapping=null;if(previousScreen==='pause')showPause();else if(previousScreen==='result'){screen='pause';finishUI();}else showHome();}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function menuAction(act){unlock();if(act==='practice'){if(g.status==='RUNNING'&&screen!=='home'){g.cut('practice');g.finish('ABANDON','进入独立练习');}start(true);return;}if(act==='start'){start(false);return;}if(act==='home'){showHome();return;}if(act==='nextHome'){seed=101+(seed-100)%4;g=new S.Game(seed);showHome();return;}if(act==='resume'){resume();return;}if(act==='cancelcount'){showPause();return;}if(act==='settings'){showSettings();return;}if(act==='back'){backSettings();return;}if(act==='backsettings'){showSettings();return;}if(act==='retry'||act==='next'){if(!canRetry())return;g.emit(act==='retry'?'retry_selected':'new_seed_selected');start(g.options.practice,act==='next'?101+(seed-100)%4:seed);return;}if(act==='abandon'){g.cut('abandon');g.finish('ABANDON','你结束了这一局。');finishUI();return;}if(act==='help'){g.emit('help_requested');readPaused=true;$('#how').scrollIntoView({behavior:'smooth'});return;}if(act==='resetkeys'){settings.keys={...defaults.keys};settings.pad={...defaults.pad};save();showSettings();return;}if(act==='debug'){showDebug();return;}if(act==='cores'){debugCores=!debugCores;debugInvalid=true;g.options.reduced_juice=true;showDebug();return;}if(act==='step'){debugInvalid=true;g.options.reduced_juice=true;g.tick({grip:g.wire!==null});showDebug();if(g.result)finishUI();return;}if(act==='selftest'){const a={x:240,y:300};const checks=[S.effective(a,{x:268,y:300})===null,S.sweptBody({x:0,y:0},{x:20,y:0},{x:10,y:0},{x:10,y:0})===.05,S.capture(a,{x:480,y:300},{x:480,y:300},{x:360,y:300},{x:360,y:300})!==null];$('#debugOut').textContent='独立几何自检：'+checks.map((c,i)=>`${i+1} ${c?'通过':'失败'}`).join('；')+'\n完整 UT01–UT20 结果见 demo/验证报告.md';return;}if(act==='export'){download('slipline1911-events.jsonl',records.map(r=>JSON.stringify(r)).join('\n')+'\n');return;}if(act==='inputs'){download('slipline1911-inputs.json',JSON.stringify({build:SLIPLINE_BUILD,runs:inputs},null,2));return;}if(act==='csv'){const cols=['session_id','seed','mode','cause','D','C','lost','time','hp','score','valid'];download('slipline1911-results.csv',cols.join(',')+'\n'+summaries.map(r=>cols.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv');return;}if(act==='erase'){records=[];inputs=[];summaries=[];$('#remapNotice').textContent='本次内存记录已清空。';return;}if(act==='observe'){if(!settings.record){$('#debugOut').textContent='请先开启本地记录。';return;}records.push({...meta(),sim_step:g.steps,sim_time:g.time,event:$('#observerEvent').value,source:'observer',notes:$('#observerNote').value});$('#debugOut').textContent='已保存人工观察；没有自动推断体验。';return;}if(act==='death'){debugCores=true;overlay.hidden=true;screen='death';$('#hint').textContent=g.result.notes;$('#pauseBtn').textContent='返回结算';return;}if(act==='formal'){start(false);return;}}
panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.remap){remapping=b.dataset.remap;$('#remapNotice').textContent='现在按一个新键；Esc 取消。';b.textContent='等待新键…';return;}if(b.dataset.act)menuAction(b.dataset.act);});
panel.addEventListener('input',e=>{const k=e.target.dataset.setting;if(!k)return;const v=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);settings[k]=v;if(k==='toggle'){virtualGrip=false;touch.grip=false;physical.delete(settings.keys.grip);if(g.wire!==null)g.cut('setting');g.armed=false;}if(k==='record'&&v){sessionId||='local-'+Date.now().toString(36);if(g.steps>0)storageNotice='当前局从开启时开始记录；完整重放请下一局启用。';}document.body.classList.toggle('reduced',settings.reduce);save();});
panel.addEventListener('change',e=>{const k=e.target.dataset.pad;if(!k)return;const v=Number(e.target.value);if(Object.entries(settings.pad).some(([other,id])=>other!==k&&id===v)){e.target.value=settings.pad[k];$('#remapNotice').textContent='手柄动作冲突，请选其他按钮。';}else{settings.pad[k]=v;save();}});
$('#pauseBtn').onclick=()=>{unlock();if(screen==='run'||screen==='countdown')pause();else if(screen==='pause')resume();else if(screen==='death'){screen='pause';finishUI();}};$('#menuBtn').onclick=()=>{if(screen==='run'||screen==='countdown')pause('菜单已打开，游戏暂停。');else if(screen==='home')showSettings();else if(screen==='pause')showSettings();else if(screen==='death'){screen='pause';finishUI();}};
function movementCode(code){return Object.entries(settings.keys).find(([k,v])=>v===code)?.[0]||{ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[code];}
function keydown(e){if(!gameEl.contains(document.activeElement))return;if(remapping){e.preventDefault();if(e.code==='Escape'){remapping=null;showSettings();return;}const taken=Object.entries(settings.keys).find(([k,v])=>k!==remapping&&v===e.code);const reserved=['Enter','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape'].includes(e.code);if(taken||reserved){$('#remapNotice').textContent='按键冲突或保留菜单键，请选其他键。';return;}settings.keys[remapping]=e.code;remapping=null;save();showSettings();return;}const inputTag=['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName);if(inputTag&&e.code!=='Escape')return;
 const action=movementCode(e.code),recognized=action||e.code==='Escape'||e.code==='Enter';if(!recognized)return;const fresh=!physical.has(e.code);physical.add(e.code);if(e.code==='Escape'||action==='pause'){e.preventDefault();if(e.repeat)return;if(screen==='run'||screen==='countdown')pause();else if(screen==='settings')backSettings();else if(screen==='debug')showSettings();else if(screen==='pause')resume();else if(screen==='death'){screen='pause';finishUI();}return;}
 if(screen==='run'){e.preventDefault();if(['up','down','left','right'].includes(action))moves.add(e.code);if(action==='grip'&&settings.toggle&&fresh&&!startGate)virtualGrip=!virtualGrip;unlock();return;}
 if(screen==='result'&&action==='retry'){e.preventDefault();if(fresh&&canRetry())menuAction('retry');return;}
 if(screen==='pause'||screen==='countdown'){if(action==='grip'||action==='focus'){if(e.target.tagName!=='BUTTON')e.preventDefault();return;}}
 if((e.code==='ArrowDown'||e.code==='ArrowUp'||e.code==='ArrowRight'||e.code==='ArrowLeft')&&!overlay.hidden){e.preventDefault();menuMove(e.code==='ArrowDown'||e.code==='ArrowRight'?1:-1);}}
function menuMove(delta){const list=[...panel.querySelectorAll('button:not(:disabled),input,select')];if(!list.length)return;const i=list.indexOf(document.activeElement);list[(i+delta+list.length)%list.length].focus();}
gameEl.addEventListener('keydown',keydown);document.addEventListener('keyup',e=>{physical.delete(e.code);moves.delete(e.code);if(e.code===settings.keys.grip){releaseSeen=true;if(screen==='run'&&!settings.toggle)g.armed=true;}});
gameEl.addEventListener('pointerdown',e=>{if(e.target===canvas||e.target===stage){uiFocus();unlock();}});
function controlButton(el,type){let pointer=null;el.addEventListener('pointerdown',e=>{if(screen!=='run'&&screen!=='countdown')return;e.preventDefault();unlock();uiFocus();pointer=e.pointerId;try{el.setPointerCapture(pointer);}catch{}if(type==='grip'&&settings.toggle){if(!startGate)virtualGrip=!virtualGrip;}else touch[type]=true;el.classList.add('pressed');});const release=e=>{if(pointer!==e.pointerId)return;pointer=null;touch[type]=false;el.classList.remove('pressed');releaseSeen=true;};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',e=>{release(e);if(type==='grip'&&settings.toggle)virtualGrip=false;});el.addEventListener('lostpointercapture',e=>{if(pointer===e.pointerId)release(e);});el.addEventListener('click',e=>e.preventDefault());}
controlButton($('#gripBtn'),'grip');controlButton($('#focusBtn'),'focus');const stick=$('#stick');function stickMove(e){if(e.pointerId!==stickPointer)return;const dx=e.clientX-stickCenter.x,dy=e.clientY-stickCenter.y,l=Math.hypot(dx,dy),r=27,q=Math.min(1,l/r);touch.x=l?dx/l*q:0;touch.y=l?dy/l*q:0;$('#stickKnob').style.transform=`translate(${touch.x*23}px,${touch.y*23}px)`;}
stick.addEventListener('pointerdown',e=>{if(screen!=='run')return;e.preventDefault();uiFocus();unlock();stickPointer=e.pointerId;const r=stick.getBoundingClientRect();stickCenter={x:r.left+r.width/2,y:r.top+r.height/2};try{stick.setPointerCapture(e.pointerId);}catch{}stickMove(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();stickMove(e);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,e=>{if(e.pointerId!==stickPointer)return;stickPointer=null;touch.x=touch.y=0;$('#stickKnob').style.transform='';});
function padPoll(){let p;try{p=[...navigator.getGamepads()].find(p=>p&&p.connected);}catch{}activePad=p||null;if(padConnected&&!p){padConnected=false;padPrev=[];pause('手柄已断开。');return;}const justConnected=!padConnected;padConnected=!!p;if(!p)return;const pressed=p.buttons.map(b=>b.pressed);if(justConnected){padPrev=pressed;return;}if(window.scrollY>8||!gameEl.contains(document.activeElement)){padPrev=pressed;return;}if(screen==='run'&&!startGate){if(settings.toggle&&pressed[settings.pad.grip]&&!padPrev[settings.pad.grip])virtualGrip=!virtualGrip;if(pressed[settings.pad.pause]&&!padPrev[settings.pad.pause])pause();}else if(!['run','countdown'].includes(screen)){if(pressed[12]&&!padPrev[12])menuMove(-1);if(pressed[13]&&!padPrev[13])menuMove(1);if(pressed[0]&&!padPrev[0])document.activeElement?.click();if(pressed[1]&&!padPrev[1]&&screen==='settings')backSettings();}padPrev=pressed;}
function heldGrip(){return physical.has(settings.keys.grip)||touch.grip||!!activePad?.buttons[settings.pad.grip]?.pressed;}
function readInput(){const held=new Set([...moves].map(movementCode));let x=Number(held.has('right'))-Number(held.has('left')),y=Number(held.has('down'))-Number(held.has('up'));const p=activePad?S.gamepadAxis(activePad.axes[0]||0,activePad.axes[1]||0):{x:0,y:0};if(touch.x||touch.y){x=touch.x;y=touch.y;}else if(p.x||p.y){x=p.x;y=p.y;}return {x,y,grip:settings.toggle?virtualGrip:heldGrip(),focus:physical.has(settings.keys.focus)||touch.focus||!!activePad?.buttons[settings.pad.focus]?.pressed,restart:physical.has(settings.keys.retry)};}
function canRetry(){return screen==='result'&&performance.now()-resultAt>=250&&resultReleased;}
function update(){const tag=mode();if(lastMode!==tag){$('#modeTag').textContent=tag;lastMode=tag;}$('#hp').textContent=Array.from({length:3},(_,i)=>i<g.hp?'●':'○').join(' ');$('#ports').textContent=`${g.completed} / 6`;$('#clock').textContent=g.options.practice?'练习':`${Math.max(0,Math.ceil(180-g.time))} 秒`;$('#score').textContent=g.score;let hint='在亮起的港口接线，拉开线接圆弹；180秒内送满六港。';const names=['西港','西北港','东北港','东港','东南港','西南港'];let current=g.wire!==null?g.ports[g.wire]:g.ports.filter(p=>p.state==='OPEN').sort((a,b)=>S.dist(a,g.player)-S.dist(b,g.player))[0];
 if(screen==='run'){if(g.options.practice){if(g.practiceSpawned&&g.hazards.length===0&&g.beads.length===0&&!g.firstDelivery)hint=g.firstCapture?'在途珠因割线丢失，还没有送达。打开菜单重看练习，或跳过。':'圆弹没碰到亮色线。打开菜单重看练习，或跳过开始正式局。';else if(!g.firstControl||g.wire===null&&!g.firstCapture)hint=`练习（免伤、不计分）：在西港${settings.toggle?'点接线':'按住接线'}。`;else if(!g.practiceSpawned)hint='保持接线，向右移动，拉出一条亮色线。';else if(!g.firstCapture)hint='让上方空心圆弹碰到亮色线；正式局身体也会受伤。';else if(!g.firstDelivery)hint='已接到圆弹！保持连接，小珠正向港口滑动。';else hint=g.wire!==null?'已实际交付！松开接线（点按模式再点一次）试试割线。':'练习成功：珠送到港才算。点击“开始正式局”。';}else if(!g.firstCapture){hint=g.wire===null?`在${current?names[current.id]:'亮圈'}${settings.toggle?'点接线':'按住接线'}，向右拉开，接上方圆弹。`:'圆弹碰亮色中段才会变珠；身体旁灰握柄接不住。';}else if(!g.firstDelivery)hint='保持连接，珠送到港才计进度；收线能让它们更快到港。';else if(g.firstNeedle&&g.steps-g.firstNeedle<480*1.6)hint='虚线是针的来路，菱针会穿线；移动身体离开它。';else hint=g.wire!==null?'保持连接收流；向港收线快送，松手割线脱身。':'寻找亮圈接线；已送到港的珠不会丢。';if(g.wire===null&&heldGrip()&&S.dist(current||g.player,g.player)>24)hint='接线需要靠近亮起的港口；保持按住，走进亮圈。';if(g.wire!==null&&S.dist(current,g.player)>239)hint='线已拉到最长；可沿港转动，或向港收线快送。';if(g.firstNeedle&&g.steps-g.firstNeedle<480*1.6)hint='虚线是针的来路，菱针会穿线；移动身体离开它。';if(g.restartSteps>0)hint='继续按住重玩，半秒后中止本局。';}
 if(screen==='pause'||screen==='settings'||screen==='debug')hint='已暂停 · 弹幕、运输和时间全部冻结。';if(screen==='countdown')hint='准备继续 · 倒数期间不计时。';if(screen==='result'||screen==='death')hint=g.result?.notes||'';
 if(lastHint!==hint){$('#hint').textContent=hint;lastHint=hint;}const info=current?`当前港 · ${names[current.id]} ${current.delivered} / 36${g.wire!==null?' · 在途 '+g.beads.length+' 颗':''}`:'所有港口已送满';if(lastWire!==info){$('#wireInfo').textContent=info;lastWire=info;}
 const gripMarkup=settings.toggle?(virtualGrip?'割线<small>在途珠会丢失</small>':'接线<small>再点一次割线</small>'):'按住接线<small>松手割线</small>';if(gripMarkup!==lastGripMarkup){$('#gripBtn').innerHTML=gripMarkup;lastGripMarkup=gripMarkup;}$('#gripBtn').classList.toggle('pressed',heldGrip()||virtualGrip);$('#focusBtn').classList.toggle('pressed',touch.focus||physical.has(settings.keys.focus));$('#pauseBtn').textContent=screen==='death'?'返回结算':screen==='pause'?'继续':'暂停';const keyMarkup=`${['up','left','down','right'].map(k=>keyLabel(settings.keys[k])).join('')} / 方向键移动<br>${keyLabel(settings.keys.grip)}接线 · ${keyLabel(settings.keys.focus)}慢走<br>按住 ${keyLabel(settings.keys.retry)} 半秒重玩`;if(keyMarkup!==lastKeyMarkup){$('#keytips').innerHTML=keyMarkup;lastKeyMarkup=keyMarkup;}
 if(g.options.practice&&g.firstDelivery&&g.wire===null&&screen==='run'){if(!$('#formalBtn')){const b=document.createElement('button');b.id='formalBtn';b.className='primary';b.textContent='开始正式局';b.onclick=()=>start(false);$('#controls').insertBefore(b,$('#gripBtn'));$('#gripBtn').hidden=true;$('#focusBtn').hidden=true;}}else{const b=$('#formalBtn');if(b)b.remove();$('#gripBtn').hidden=false;$('#focusBtn').hidden=false;}
}
function resize(){const r=stage.getBoundingClientRect(),s=getComputedStyle(stage),w=r.width-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),h=r.height-parseFloat(s.paddingTop)-parseFloat(s.paddingBottom);scale=Math.max(.05,Math.min(w/960,h/600));canvas.style.width=960*scale+'px';canvas.style.height=600*scale+'px';const dpr=window.devicePixelRatio||1;canvas.width=Math.round(960*scale*dpr);canvas.height=Math.round(600*scale*dpr);if(screen==='run'||screen==='countdown')pause('窗口尺寸改变了，请确认继续。');}
new ResizeObserver(resize).observe(stage);window.addEventListener('blur',()=>{physical.clear();pause('窗口失去焦点。');});document.addEventListener('visibilitychange',()=>{if(document.hidden){physical.clear();pause('页面暂时离开。');}});window.addEventListener('scroll',()=>{if(window.scrollY>8&&gameEl.contains(document.activeElement))document.activeElement.blur();if(window.scrollY>8&&(screen==='run'||screen==='countdown')){readPaused=true;pause('正在阅读下方说明，游戏已暂停。');}},{passive:true});document.addEventListener('pointerdown',e=>{if(!gameEl.contains(e.target)&&(screen==='run'||screen==='countdown'))pause('已离开游戏区域。');});document.querySelectorAll('.returnGame').forEach(b=>b.onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});readPaused=false;uiFocus();if(screen==='pause')showPause();});
// Drawing follows state; no animation changes collisions or scores.
function line(a,b,color,width=2,dash=[]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}
function circle(x,y,r,color,fill=false,width=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=color;ctx.fill();}else{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}}
function text(t,x,y,color='#a7b5c5',px=12){ctx.fillStyle=color;ctx.font=`500 ${px/scale}px system-ui,sans-serif`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function draw(){const dpr=window.devicePixelRatio||1;ctx.setTransform(canvas.width/960,0,0,canvas.height/600,0,0);ctx.fillStyle='#101722';ctx.fillRect(0,0,960,600);if(!settings.reduce&&!g.options.reduced_juice){const hit=g.fx.findLast(f=>f.kind==='hit'),age=hit?(g.steps-hit.step)/480:1;if(age<.12)ctx.translate(Math.sin(age*120)*2*(1-age/.12),0);}ctx.lineCap='round';const minStroke=1/scale;ctx.strokeStyle='#253448';ctx.lineWidth=.65;for(let x=0;x<=960;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke();}for(let y=0;y<=600;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke();}
 // Quiet boundary marks and fixed ports.
 for(const p of g.ports){const open=p.state==='OPEN',complete=p.state==='COMPLETE',opening=p.state==='OPENING',color=open||opening?'#67d9d0':'#647184';circle(p.x,p.y,24,color,false,open?Math.max(1.2,minStroke):1);if(open){circle(p.x,p.y,30,'#67d9d025',false,3);for(let i=0;i<36;i++){const a=-Math.PI/2+i*Math.PI*2/36;line({x:p.x+19*Math.cos(a),y:p.y+19*Math.sin(a)},{x:p.x+23*Math.cos(a),y:p.y+23*Math.sin(a)},i<p.delivered?'#d7fff2':'#35535c',Math.max(1,minStroke));}if(g.wire===p.id)circle(p.x,p.y,7,'#67d9d0',true);else{line({x:p.x-6,y:p.y},{x:p.x+6,y:p.y},color,2);line({x:p.x,y:p.y-6},{x:p.x,y:p.y+6},color,2);}text(`${p.delivered}/36`,p.x,p.y+24+14/scale,color,11);}else if(complete){line({x:p.x-9,y:p.y},{x:p.x-2,y:p.y+6},color,2);line({x:p.x-2,y:p.y+6},{x:p.x+10,y:p.y-7},color,2);}else if(opening){const remaining=Math.max(0,(p.openAt-g.steps)/480);text(remaining.toFixed(1),p.x,p.y+4/scale,color,12);}else{line({x:p.x-7,y:p.y-7},{x:p.x+7,y:p.y+7},color,1.3);line({x:p.x+7,y:p.y-7},{x:p.x-7,y:p.y+7},color,1.3);}}
 for(const w of g.warnings)for(const s of w.shots){const o={x:S.clamp(s.x,4,956),y:S.clamp(s.y,4,596)};if(s.type==='NEEDLE'){const length=1200;line(o,{x:s.x+s.dx*length,y:s.y+s.dy*length},'#f27e9d90',Math.max(1,minStroke*.75),[6,8]);circle(o.x,o.y,9,'#f27e9d',false,2);}else{line(o,{x:o.x+s.dx*24,y:o.y+s.dy*24},'#ffc66d88',2);}}
 // Residue is visibly broken and only decorative.
 for(const f of g.fx){const age=(g.steps-f.step)/480;if(f.kind==='cut'&&age<.12){line(f.a,f.p,`rgba(100,113,132,${(1-age/.12)*.6})`,2,[5,9]);if(!settings.reduce&&!g.options.reduced_juice)for(const b of f.discarded||[])circle(b.x,b.y+age*30,2.5,`rgba(215,255,242,${1-age/.12})`,true);}if(f.kind==='complete'&&age<.45){line(f.a,f.p,`rgba(103,217,208,${(1-age/.45)*.18})`,52);circle(f.a.x,f.a.y,90,'#67d9d035',false,2);}}
 if(g.wire!==null){const a=g.ports[g.wire],p=g.player,l=S.dist(a,p),e=S.effective(a,p);line(a,p,'#080e16',8);if(l>0){line(a,S.lerp?S.lerp(a,p,8/l):{x:a.x+(p.x-a.x)*Math.min(1,8/l),y:a.y+(p.y-a.y)*Math.min(1,8/l)},'#647184',4);if(e){line(e.s,e.e,'#67d9d0',4);for(let i=20;i<l-20;i+=28){const u=(i-(g.steps/480*28)%28)/l,pos={x:a.x+(p.x-a.x)*u,y:a.y+(p.y-a.y)*u};circle(pos.x,pos.y,1.5,'#d7fff2',true);}line(e.e,p,'#647184',5,[4,4]);}else line(a,p,'#647184',4,[4,4]);}for(const b of g.beads){const u=Math.max(0,b.u);circle(a.x+(p.x-a.x)*u,a.y+(p.y-a.y)*u,Math.max(2.5,1.25/scale),'#d7fff2',true);}}
 // Small visual rims at compact sizes improve visibility; hit cores remain 4.
 for(const b of g.hazards){const v=Math.hypot(b.vx,b.vy)||1,dx=b.vx/v,dy=b.vy/v;if(b.type==='ROUND'){line({x:b.x-dx*10,y:b.y-dy*10},b,'#ffc66d55',1.5);circle(b.x,b.y,Math.max(4,1.9/scale),'#ffc66d',false,Math.max(1.5,1/scale));}else{line({x:b.x-dx*24,y:b.y-dy*24},b,'#f27e9d80',Math.max(1,1/scale));const side=3;ctx.beginPath();ctx.moveTo(b.x+dx*8,b.y+dy*8);ctx.lineTo(b.x-dy*side,b.y+dx*side);ctx.lineTo(b.x-dx*8,b.y-dy*8);ctx.lineTo(b.x+dy*side,b.y-dx*side);ctx.closePath();ctx.fillStyle='#f27e9d';ctx.fill();circle(b.x,b.y,2,'#fff5f5',true);}if(debugCores)circle(b.x,b.y,4,'#ff3b66',false,1);}
 const p=g.player;ctx.save();ctx.translate(p.x,p.y);const motion=Math.hypot(p.vx,p.vy);if(motion)bodyAngle=Math.atan2(p.vy,p.vx);const drawNow=performance.now(),elapsed=(drawNow-lastDrawTime)/1000;lastDrawTime=drawNow;const target=settings.reduce?1:1+.12*Math.min(1,motion/260);bodyStretch=motion?target:Math.max(1,bodyStretch-.12*elapsed/.08);ctx.rotate(bodyAngle);ctx.scale(bodyStretch,1);ctx.strokeStyle='#f4f0dd';ctx.lineWidth=Math.max(2,1.3/scale);ctx.beginPath();ctx.moveTo(-9,-4);ctx.quadraticCurveTo(-4,-14,3,-8);ctx.lineTo(12,0);ctx.lineTo(3,8);ctx.quadraticCurveTo(-4,14,-9,4);ctx.stroke();ctx.restore();circle(p.x,p.y,5,'#f4f0dd',true);if(g.invuln>0){ctx.beginPath();ctx.arc(p.x,p.y,16,-Math.PI/2,-Math.PI/2+Math.PI*2*g.invuln/480);ctx.strokeStyle='#f4f0dd';ctx.lineWidth=Math.max(1.4,minStroke);ctx.stroke();}
 if(debugCores){circle(p.x,p.y,5,'#ff3b66',false,1);if(g.wire!==null)circle(g.ports[g.wire].x,g.ports[g.wire].y,240,'#ffffff45',false,1);}if(screen==='death'&&g.lastHit){circle(g.lastHit.x,g.lastHit.y,9,'#f27e9d',false,Math.max(2,minStroke));circle(p.x,p.y,13,'#f4f0dd',false,2);}
 for(const f of g.fx){const age=(g.steps-f.step)/480;if(f.kind==='capture'&&age<.12){circle(f.x,f.y,5+age*45,'#d7fff2',false,1);if(!settings.reduce&&!g.options.reduced_juice&&S.dist(f,g.player)>24)for(let n=0;n<3;n++){const a=n*Math.PI*2/3,r=5+age*70;line({x:f.x+Math.cos(a)*r,y:f.y+Math.sin(a)*r},{x:f.x+Math.cos(a)*(r+3),y:f.y+Math.sin(a)*(r+3)},'#67d9d0',1);}}if(f.kind==='deliver'&&age<.1)circle(f.x,f.y,26+age*35,'#d7fff260',false,2);if(f.kind==='attach'&&age<.08)circle(f.x,f.y,16-age*100,'#67d9d0',false,2);if(f.kind==='hit'&&age<.12)circle(f.x,f.y,20+age*130,'#f27e9d',false,2);}
 if(screen==='run'&&g.wire===null&&!g.firstControl){const a=g.ports[g.seed.start_port];text('你在这里 · 接线后向右',a.x,a.y-45/scale,'#f4f0dd',12);}if(g.options.practice)text('练习 · 免伤 / 不计分',480,27/scale,'#67d9d0',12);
}
function frame(now){const delta=lastFrame?(now-lastFrame)/1000:0;lastFrame=now;padPoll();if(screen==='countdown'){const remain=Math.max(0,countEnd-now);if($('#countNumber'))$('#countNumber').textContent=remain>0?'1':'开始';if(now>=countEnd){screen='run';overlay.hidden=true;sound.muted=false;accumulator=0;g.emit('resume');uiFocus();if(g.wire===null)g.armed=releaseSeen;}}
 if(screen==='run'){if(startGate){if(!heldGrip()&&physical.size===0&&!activePad?.buttons.some(b=>b.pressed)){startGate=false;releaseSeen=true;g.armed=true;}accumulator=0;}else{accumulator+=delta;if(accumulator>2){g.invalid('固定步追赶积压超过2秒，未跳过模拟时间');finishUI();}else{while(accumulator>=1/120&&screen==='run'){const i=readInput();if(settings.record){let run=inputs.find(r=>r.session_id===sessionId);if(!run){run={session_id:sessionId,seed:g.seed.id,options:{...g.options},from_step:g.steps,ticks:[]};inputs.push(run);}run.ticks.push({...i,tick:g.tickIndex+1,step:g.steps});}g.tick(i);accumulator-=1/120;for(const f of g.fx){const id=f.step+':'+f.kind+':'+(f.x||0)+':'+(f.level||0);if(!playedFx.has(id)){sound.play(f);playedFx.add(id);}}if(playedFx.size>500)playedFx=new Set([...playedFx].slice(-200));if(g.result){if(g.result.cause==='ABANDON'&&g.restartSteps>=240){pendingHoldRetry=true;finishUI();}else finishUI();}}sound.ambient();}}}
 if(screen==='result'){if(!heldGrip()&&!physical.has(settings.keys.retry)&&!physical.has('Enter')&&!activePad?.buttons[0]?.pressed)resultReleased=true;if(canRetry()){for(const b of panel.querySelectorAll('[data-act="retry"],[data-act="next"]')){const wasDisabled=b.disabled;b.disabled=false;if(wasDisabled&&b.dataset.act==='retry')b.focus({preventScroll:true});}if(pendingHoldRetry){pendingHoldRetry=false;start(g.options.practice);}}}
 update();draw();requestAnimationFrame(frame);}
// Read-only diagnostics and explicit debug APIs, used by local verification only.
window.SLIPLINE_APP={get game(){return g;},get screen(){return screen;},get settings(){return settings;},get records(){return records;},get inputs(){return inputs;},get audioState(){return {voices:sound.voices.length,state:sound.context?.state||'locked',musicLast:sound.musicLast};},start,pause,resume,showHome,showSettings,readInput,canRetry,debugFixture(fn){pause('调试夹具');debugInvalid=true;g.options.reduced_juice=true;fn(g);if(g.result)finishUI();draw();},replay(run){if(run.from_step!==0)throw Error('记录从局中开始，不能完整重放');const replay=new S.Game(run.seed,run.options);replay.armed=true;for(const i of run.ticks)replay.tick(i);return replay.snapshot();}};
document.body.classList.toggle('reduced',settings.reduce);showHome();resize();requestAnimationFrame(frame);
})();
