/* SLIPLINE 1911: deterministic rules. Rendering and sound never submit rules. */
(function(root){
'use strict';
const C=root.SLIPLINE_CONFIG||(typeof require==='function'?require('./config.js'):null);
const hz=C.simulation.simulation_hz,dt=1/hz;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
// Decimal event seconds are rounded up, with floating representation noise removed.
const at=t=>Math.ceil(t*hz-1e-9);
const lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
function segmentDistance(p,a,b){const x=b.x-a.x,y=b.y-a.y,l=x*x+y*y;const u=l?clamp(((p.x-a.x)*x+(p.y-a.y)*y)/l,0,1):0;return Math.hypot(p.x-a.x-u*x,p.y-a.y-u*y);}
function sweptBody(b0,b1,p0,p1){const x=b0.x-p0.x,y=b0.y-p0.y,dx=b1.x-b0.x-p1.x+p0.x,dy=b1.y-b0.y-p1.y+p0.y;const a=dx*dx+dy*dy,b=2*(x*dx+y*dy),c=x*x+y*y-C.collision.body_radius_sum_squared;if(c<=0)return 0;if(a<=C.collision.stationary_relative_motion_epsilon_squared)return null;const d=b*b-4*a*c;if(d<0)return null;const q=(-b-Math.sqrt(d))/(2*a);return q>=0&&q<=1?q:null;}
function effective(a,p){const l=dist(a,p);if(l<=C.wire.minimum_capture_length_exclusive)return null;return {s:lerp(a,p,C.wire.anchor_dead_length/l),e:lerp(a,p,1-C.wire.player_dead_length/l),l};}
function capture(a,p0,p1,b0,b1,samples=C.collision.capture_sample_fractions){for(const q of samples){const p=lerp(p0,p1,q),b=lerp(b0,b1,q),line=effective(a,p);if(!line)continue;if(segmentDistance(b,line.s,line.e)<=C.hazards.round_radius+C.wire.width/2+C.simulation.capture_epsilon){const x=p.x-a.x,y=p.y-a.y;return {q,u:clamp(((b.x-a.x)*x+(b.y-a.y)*y)/(x*x+y*y),0,1),x:b.x,y:b.y};}}return null;}
function gamepadAxis(x,y){const l=Math.hypot(x,y),m=clamp((l-C.player.gamepad_deadzone)/(1-C.player.gamepad_deadzone),0,1);return l?{x:x/l*m,y:y/l*m}:{x:0,y:0};}
function origin(edge,q=0){const n=C.director.edge_normals[edge],c=C.director.edge_centers[edge],s=C.director.half_spans[edge];return {x:c[0]+q*s*n[1],y:c[1]-q*s*n[0]};}
function direction(edge,degrees=0){const n=C.director.edge_normals[edge],r=degrees*Math.PI/180;return {x:n[0]*Math.cos(r)-n[1]*Math.sin(r),y:n[0]*Math.sin(r)+n[1]*Math.cos(r)};}
class Game{
 constructor(seed=101,options={}){this.options={ease:false,instant_delivery:false,reduced_juice:false,practice:false,...options};this.seed=C.seeds.find(s=>s.id===seed)||C.seeds[0];this.steps=0;this.tickIndex=0;this.status='RUNNING';this.result=null;this.hp=C.player.hp_max;this.invuln=0;this.D=0;this.completed=0;this.score=0;this.lost=0;this.wire=null;this.armed=false;this.hazards=[];this.beads=[];this.events=[];this.eventSink=null;this.fx=[];this.warnings=[];this.schedule=[];this.scheduleId=0;this.nextId=1;this.restartSteps=0;this.queue=[...this.seed.queue];this.ports=C.ports.positions.map(p=>({...p,state:C.ports.initial_active_ids.includes(p.id)?'OPEN':'CLOSED',delivered:0,openAt:0,pulse:0}));const p=this.ports[this.seed.start_port];this.player={x:p.x,y:p.y,vx:0,vy:0};this.firstControl=false;this.firstCapture=false;this.firstDelivery=false;this.firstNeedle=null;this.practiceSpawned=false;this.maxHazards=0;this.maxBeads=0;this.lastHit=null;this.error=null;if(!options.practice)this.plan();this.emit('run_start');}
 get time(){return this.steps/hz;}
 get valid(){return !this.options.practice&&!this.options.instant_delivery&&!this.options.reduced_juice&&this.status!=='INVALID_TECH';}
 groupKey(){return this.seed.id+':'+(this.options.ease?'.8':'1')+':'+(root.SLIPLINE_BUILD?.config_hash||'config');}
 emit(event,data={}){const e={sim_step:this.eventStep??this.steps,sim_time:(this.eventStep??this.steps)/hz,event,source:'auto',hp:this.hp,delivered_total:this.D,completed_total:this.completed,beads_in_flight:this.beads.length,x:this.player.x,y:this.player.y,...data};this.events.push(e);if(this.events.length>100)this.events.shift();if(this.eventSink)this.eventSink(e);}
 feedback(kind,data={}){this.fx.push({kind,step:this.eventStep??this.steps,...data});if(this.fx.length>96)this.fx.shift();}
 add(t,kind,data){this.schedule.push({step:at(t),kind,data,seq:this.scheduleId++});this.schedule.sort((a,b)=>a.step-b.step||a.seq-b.seq);}
 plan(){const d=C.director;for(let j=0;j*d.phrase_seconds<C.session.limit_seconds;j++){const t=j*d.phrase_seconds,r=this.seed.edges[j%4];for(const [offset,type] of [[d.comb_times[0]-d.comb_warning,'comb'],[d.fan_times[0]-d.fan_warning,'fan'],[d.braid_start-d.braid_warning,'braid'],[d.rail_warning_local,'rail']])this.add(t+offset,'warning',{type,j,r,t});}for(let m=0;d.pin_first_warning+m*d.pin_warning_interval<C.session.limit_seconds;m++)this.add(d.pin_first_warning+m*d.pin_warning_interval,'warning',{type:'pin',m,t:d.pin_first_warning+m*d.pin_warning_interval});}
 warn(data){const d=C.director,k=clamp(this.completed,0,5),type=data.type,t=data.t,r=data.r;const speed=(type==='pin'||type==='rail'?C.hazards.needle_speed_by_completed:C.hazards.round_speed_by_completed)[k]*(this.options.ease?.8:1);let shots=[],fire=[];
 if(type==='comb'){fire=d.comb_times.map(v=>t+v);if(k>=4)fire.push(t+d.comb_extra_time_from_completed_4);}
 if(type==='fan'){const e=(r+d.fan_edge_offset)%4;shots=(k<=1?d.fan_degrees_tier_0_1:d.fan_degrees_tier_2_5).map(a=>({...origin(e),...{dir:direction(e,a)},type:'ROUND'})).map(s=>({...s,x:s.x,y:s.y,dx:s.dir.x,dy:s.dir.y}));fire=d.fan_times.map(v=>t+v);}
 if(type==='braid'){for(let i=0;i<d.braid_count;i++){const pair=d.braid_edge_offsets.map((off,z)=>({pos:origin((r+off)%4,d.braid_q[z]),dir:direction((r+off)%4,d.braid_angles[i%4]*(z?-1:1)),type:'ROUND'}));const normalized=pair.map(s=>({x:s.pos.x,y:s.pos.y,dx:s.dir.x,dy:s.dir.y,type:s.type}));this.add(t+d.braid_start+i*d.braid_interval,'spawn',{shots:normalized,speed,k,type});if(i===0)shots=normalized;}fire=[t+d.braid_start];}
 if(type==='pin'){const e=(this.seed.edges[data.m%4]+d.pin_edge_offset)%4,p=origin(e,d.pin_q_even_odd[data.m%2]),angle=Math.atan2(this.player.y-p.y,this.player.x-p.x);shots=(k<=2?d.pin_angles_tier_0_2:d.pin_angles_tier_3_5).map(a=>({x:p.x,y:p.y,dx:Math.cos(angle+a*Math.PI/180),dy:Math.sin(angle+a*Math.PI/180),type:'NEEDLE'}));fire=[t+d.pin_warning_seconds];}
 if(type==='rail'){if(k<d.rail_from_completed)return;const e=(r+d.rail_edge_offset)%4;shots=d.rail_q.map(q=>({...origin(e,q),dx:direction(e).x,dy:direction(e).y,type:'NEEDLE'}));fire=[t+d.rail_warning_local+d.rail_warning_seconds];}
 // The comb's position and direction must be kept separate.
 if(type==='comb'){const n=d.comb_candidate_counts[r],g=(d.comb_gap_phrase_factor*data.j+this.seed.gap_offset)%(n-3),norm=C.director.edge_normals[r],c=origin(r);shots=[];for(let i=0;i<n;i++){if(i>=g&&i<g+d.comb_gap_slots)continue;const s=(i-(n-1)/2)*d.comb_spacing;shots.push({x:c.x+s*norm[1],y:c.y-s*norm[0],dx:norm[0],dy:norm[1],type:'ROUND'});}}
 if(type!=='braid')for(const f of fire)this.add(f,'spawn',{shots,speed,k,type});const until=at(fire[0]);this.warnings.push({type,k,speed,shots,until,step:this.eventStep});if(type==='pin'||type==='rail'){this.firstNeedle??=this.eventStep;this.emit('needle_warning',{notes:type,object_id:data.m??data.j});this.feedback('needle');this.add(fire[0]-C.feedback.needle_audio_warning_remaining_seconds[1],'beep',{});}
 }
 spawn(type,x,y,vx,vy){if(this.hazards.length>=C.simulation.hostile_capacity){this.invalid('危险容量超过512');return null;}const b={id:this.nextId++,type,x,y,px:x,py:y,vx,vy,born:this.eventStep??this.steps};this.hazards.push(b);this.maxHazards=Math.max(this.maxHazards,this.hazards.length);return b;}
 invalid(message){this.error=message;this.emit('tech_invalid',{notes:message});this.finish('INVALID_TECH',message);}
 attach(){if(this.wire!==null||!this.armed)return;const ports=this.ports.filter(p=>p.state==='OPEN'&&dist(p,this.player)<=C.wire.attach_radius).sort((a,b)=>dist(a,this.player)-dist(b,this.player)||a.id-b.id);if(!ports.length)return;this.wire=ports[0].id;this.armed=false;this.emit('grip_attach',{port_id:this.wire});this.feedback('attach',{x:this.player.x,y:this.player.y});}
 cut(cause='release'){if(this.wire===null)return;const p=this.ports[this.wire],end={...this.player},count=this.beads.length,discarded=this.beads.map(b=>({x:p.x+(end.x-p.x)*Math.max(0,b.u),y:p.y+(end.y-p.y)*Math.max(0,b.u),id:b.id}));this.lost+=count;if(count)this.emit('beads_discard',{cause,port_id:this.wire,notes:String(count)});this.beads=[];this.emit('grip_release',{cause,port_id:this.wire});this.feedback('cut',{a:{x:p.x,y:p.y},p:end,count,discarded});this.wire=null;this.armed=false;}
 finish(cause,notes=''){if(this.status!=='RUNNING')return;this.status=cause;const time=(this.eventStep??this.steps)/hz;this.score=C.score.per_delivered*this.D+C.score.per_completed_port*this.completed;if(cause==='CLEAR')this.score+=C.score.clear_bonus+C.score.clear_per_remaining_whole_second*Math.floor(Math.max(0,C.session.limit_seconds-time))+C.score.clear_per_hp*this.hp;this.result={cause,notes,time,hp:this.hp,D:this.D,C:this.completed,lost:this.lost,score:this.score,valid:this.valid,seed:this.seed.id};this.emit('result',{cause,notes});this.feedback(cause==='CLEAR'?'clear':'result');}
 tick(input={}){if(this.status!=='RUNNING')return;let x=clamp(Number(input.x)||0,-1,1),y=clamp(Number(input.y)||0,-1,1),l=Math.hypot(x,y);if(l>1){x/=l;y/=l;}const i={x,y,grip:!!input.grip,focus:!!input.focus,restart:!!input.restart};this.tickIndex++;this.eventStep=this.steps+1;if(!i.restart)this.restartSteps=0;if(i.restart&&this.restartSteps>=at(C.session.in_run_restart_hold_seconds)){this.cut('restart');this.finish('ABANDON','按住重玩，已中止这一局');return;}if(i.restart)this.restartSteps+=C.simulation.substeps_per_tick;
 if(!i.grip){this.cut('release');this.armed=true;}for(let s=0;s<C.simulation.substeps_per_tick&&this.status==='RUNNING';s++)this.substep(i);}
 substep(i){this.eventStep=this.steps+1;const oldBeads=new Set(this.beads.map(b=>b.id));if(this.invuln>0)this.invuln--;if(i.grip)this.attach();for(const p of this.ports)if(p.state==='OPENING'&&p.openAt<=this.eventStep){p.state='OPEN';this.emit('port_open',{port_id:p.id});}
 while(this.schedule.length&&this.schedule[0].step<=this.eventStep&&this.status==='RUNNING'){const e=this.schedule.shift();if(e.kind==='warning')this.warn(e.data);if(e.kind==='spawn')for(const s of e.data.shots){this.spawn(s.type,s.x,s.y,s.dx*e.data.speed,s.dy*e.data.speed);if(this.status!=='RUNNING')break;}if(e.kind==='beep')this.feedback('needle');}if(this.status!=='RUNNING')return;
 const p0={x:this.player.x,y:this.player.y},speed=i.focus?C.player.focus_speed:C.player.move_speed,m=C.viewport.player_margin;this.player.vx=i.x*speed;this.player.vy=i.y*speed;this.player.x=clamp(p0.x+i.x*speed*dt,m,C.viewport.arena_width-m);this.player.y=clamp(p0.y+i.y*speed*dt,m,C.viewport.arena_height-m);if(this.wire!==null){const a=this.ports[this.wire],length=dist(a,this.player);if(length>C.wire.max_length){this.player.x=a.x+(this.player.x-a.x)*C.wire.max_length/length;this.player.y=a.y+(this.player.y-a.y)*C.wire.max_length/length;}}
 if(!this.firstControl&&(i.x||i.y||i.grip)){this.firstControl=true;this.emit('first_control');}
 if(this.options.practice&&this.wire!==null&&!this.practiceSpawned&&this.player.x>340){this.practiceSpawned=true;for(const x of [310,330,350])this.spawn('ROUND',x,235,0,140);}
 const p1=this.player;let hit=null;for(const b of this.hazards){b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;if(!this.invuln&&!this.options.practice){const q=sweptBody({x:b.px,y:b.py},b,p0,p1);if(q!==null&&(!hit||q<hit.q||(q===hit.q&&b.id<hit.b.id)))hit={b,q};}}
 if(hit){this.hp--;this.lastHit={...hit.b,q:hit.q,body0:p0,body1:{x:p1.x,y:p1.y},step:this.eventStep};this.hazards=this.hazards.filter(b=>b.id!==hit.b.id&&dist(b,p1)>C.player.hurt_clear_radius);this.emit('hit',{cause:hit.b.type,object_id:hit.b.id});this.feedback('hit',{x:p1.x,y:p1.y});this.cut('hit');this.invuln=at(C.player.hurt_invulnerability);if(this.hp===0)this.finish('FAILED_HIT',hit.b.type==='NEEDLE'?'菱针命中了身体，导线挡不住菱针。':'圆弹未被有效线段接住，命中了身体。');}
 else if(this.wire!==null){const a=this.ports[this.wire],caught=new Set();for(const b of this.hazards){if(b.type!=='ROUND')continue;const c=capture(a,p0,p1,{x:b.px,y:b.py},b);if(!c)continue;if(this.beads.length>=C.simulation.bead_capacity){this.invalid('在途珠容量超过128');break;}caught.add(b.id);const bead={id:b.id,u:this.options.instant_delivery?0:c.u,port_id:this.wire};this.beads.push(bead);if(this.options.instant_delivery)oldBeads.add(bead.id);this.firstCapture=true;this.emit('round_capture',{object_id:b.id,port_id:this.wire});this.feedback('capture',{x:c.x,y:c.y});}this.hazards=this.hazards.filter(b=>!caught.has(b.id));this.maxBeads=Math.max(this.maxBeads,this.beads.length);if(this.status==='RUNNING'){const L=dist(a,this.player),arrived=[];for(const b of this.beads)if(oldBeads.has(b.id)){b.u-=C.wire.bead_speed*dt/Math.max(L,C.wire.transport_denominator_floor);if(b.u<=0)arrived.push(b);}arrived.sort((a,b)=>a.id-b.id);const done=new Set();for(const b of arrived){if(a.delivered>=C.ports.capacity_each)break;done.add(b.id);a.delivered++;this.D++;this.firstDelivery=true;this.emit('bead_deliver',{object_id:b.id,port_id:a.id});this.feedback('deliver',{x:a.x,y:a.y,level:a.delivered});a.pulse=this.eventStep;}this.beads=this.beads.filter(b=>!done.has(b.id));if(a.delivered===C.ports.capacity_each){a.state='COMPLETE';this.completed++;this.emit('port_complete',{port_id:a.id});this.feedback('complete',{a:{x:a.x,y:a.y},p:{x:this.player.x,y:this.player.y}});this.hazards=this.hazards.filter(b=>dist(b,a)>C.ports.completion_clear_radius&&segmentDistance(b,a,this.player)>C.ports.completion_clear_corridor_radius);this.cut('complete');const next=this.queue.shift();if(next!==undefined){const port=this.ports[next];port.state='OPENING';port.openAt=this.eventStep+at(C.ports.activation_delay);this.emit('port_opening',{port_id:next});}}}}
 this.steps=this.eventStep;this.score=C.score.per_delivered*this.D+C.score.per_completed_port*this.completed;if(this.status==='RUNNING'){if(this.completed===C.session.ports_to_clear)this.finish('CLEAR','六个港口都已送满。');else if(this.time>=C.session.limit_seconds)this.finish('FAILED_TIME','180秒到了，还没有送满六港。');}if(this.result)this.score=this.result.score;const margin=C.hazards.cull_margin;this.hazards=this.hazards.filter(b=>this.steps-b.born<at(C.hazards.ttl)&&b.x>=-margin&&b.x<=C.viewport.arena_width+margin&&b.y>=-margin&&b.y<=C.viewport.arena_height+margin);this.warnings=this.warnings.filter(w=>w.until>this.steps);this.fx=this.fx.filter(f=>this.steps-f.step<hz*.6);}
 snapshot(){return {seed:this.seed.id,steps:this.steps,hp:this.hp,invuln:this.invuln,D:this.D,C:this.completed,score:this.score,lost:this.lost,status:this.status,wire:this.wire,armed:this.armed,player:{...this.player},ports:this.ports.map(p=>({...p})),hazards:this.hazards.map(b=>({...b})),beads:this.beads.map(b=>({...b})),schedule:this.schedule.map(e=>({...e})),queue:[...this.queue]};}
}
const api={Game,C,hz,dt,at,clamp,dist,segmentDistance,sweptBody,effective,capture,gamepadAxis,origin,direction};root.Slipline=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
