(function(){
'use strict';
const C=Turnline,$=id=>document.getElementById(id),game=$('game'),canvas=$('board'),ctx=canvas.getContext('2d'),stage=$('stage');
let settings={toggle:false,preview:true,sound:true,particles:true,shake:true,hitstop:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
let recipe=C.expand(20261002),world,tutorial,armed=false,keys=new Set(),spaceHeld=false,pendingMove=null,joy=[0,0],press=false,release=false,anchorPointers=new Set(),joyPointer=null,joyOrigin=null,overlayKind='',returnKind='',lastStamp=0,accum=0,hitstop=0,fx=[],lastEvent=0,lastFeedback='',feedbackUntil=0,audio=null,runNumber=0,history=[];
function focusGame(){if(scrollY>8)window.scrollTo({top:0,behavior:'instant'});game.focus({preventScroll:true});armed=true;}
function unlockAudio(){if(!settings.sound)return;try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}catch(e){settings.sound=false;}}
function tone(type){if(!settings.sound||!audio)return;const notes={anchor_started:[310,.035],redirected:[145,.11],dock_delivered:[620,.12],player_hit:[80,.16],warning:[420,.04],lost:[120,.07],contract_end:[780,.16],contract_fail:[110,.19]};if(!notes[type])return;try{const [f,d]=notes[type],o=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime;o.type=type==='player_hit'?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*(type==='dock_delivered'?1.5:.65),t+d);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.13,t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(gain);gain.connect(audio.destination);o.start(t);o.stop(t+d+.01);}catch(e){}}
function tell(text,seconds=2){lastFeedback=text;feedbackUntil=world.time+seconds;$('feedback').textContent=text;}
function clearInput(){keys.clear();spaceHeld=false;pendingMove=null;joy=[0,0];press=false;release=false;anchorPointers.clear();joyPointer=null;joyOrigin=null;$('stick').style.transform='';$('anchor').classList.remove('pressed');if(world)world.clearInput();}
function start(mode,keep=true){clearInput();if(!keep){const old=recipe.sequence.map(r=>r.id).join(',');let candidate;do{const seed=(Date.now()^Math.floor(Math.random()*4294967296))>>>0;candidate=C.expand(seed);}while(candidate.sequence.map(r=>r.id).join(',')===old);recipe=candidate;}world=new C.World(recipe,mode);tutorial=mode==='tutorial'?{index:0,phase:'move',heldExample:false}:null;lastEvent=0;fx=[];accum=0;hitstop=0;runNumber++;lastFeedback='';feedbackUntil=0;hidePanel();focusGame();updateHUD();}
function restartTeaching(index=0){start('tutorial');tutorial.index=index;world.nextId=index;world.contract.delivered=index;for(let i=0;i<index;i++)world.contract.settled.add(i);if(index)world.p=[554,266];updateHUD();}
function pause(reason='手动暂停'){if(overlayKind||world.contract.status!=='active')return;clearInput();world.setPause(true);showPanel('pause',reason);}
function hidePanel(){overlayKind='';$('overlay').hidden=true;$('panelBody').innerHTML='';$('panelActions').innerHTML='';if(world)world.setPause(false);accum=0;lastStamp=0;}
function action(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.addEventListener('click',e=>{e.stopPropagation();unlockAudio();fn();});$('panelActions').appendChild(b);return b;}
function showPanel(kind,reason=''){overlayKind=kind;world.setPause(true);clearInput();$('overlay').hidden=false;$('panelBody').innerHTML='';$('panelActions').innerHTML='';$('closePanel').hidden=['result','tutorialDone','tutorialFail','diagnostic'].includes(kind);const body=$('panelBody');
 if(kind==='pause'){ $('panelTitle').textContent='作业已暂停';body.innerHTML='<p>'+reason+'。来件和计时都停在原处。</p><p>继续后需要重新按下立锚，不会执行之前的按键。</p>';action('继续作业',()=>{hidePanel();focusGame();},true);action('重玩这一局',()=>start(world.mode));action('菜单',()=>showPanel('menu'));}
 if(kind==='menu'){ $('panelTitle').textContent='作业菜单';body.innerHTML='<p>正式作业：8件送入5件，耐久3，限时180秒。</p><div class="menu-grid"></div>';const grid=body.querySelector('.menu-grid');for(const [label,fn] of [['开始正式作业',()=>start('standard')],['慢速练习',()=>start('practice')],['重玩这一局',()=>start(world.mode)],['换新配方',()=>start(world.mode==='tutorial'?'standard':world.mode,false)],['重看安全教学',()=>restartTeaching()],['操作与反馈设置',()=>{returnKind='menu';showPanel('settings');}]]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;grid.appendChild(b);}body.insertAdjacentHTML('beforeend','<p class="subheading">慢速练习仍有8件，不记正式成绩。重玩保留来件顺序。</p>');action('返回游戏',()=>{hidePanel();focusGame();},true);}
 if(kind==='settings'){ $('panelTitle').textContent='操作与反馈';body.innerHTML='<p>动作方式</p>';const options=[['toggle','按一下立锚，再按收线'],['preview','显示当前角度的出路预览'],['sound','声音'],['particles','截击粒子'],['shake','轻微震动'],['hitstop','接住时短暂停顿'],['reduced','减少运动（关粒子与震动）']];for(const [key,label] of options){const row=document.createElement('label'),span=document.createElement('span'),box=document.createElement('input');span.textContent=label;box.type='checkbox';box.checked=settings[key];box.onchange=()=>{settings[key]=box.checked;clearInput();if(key==='sound'&&box.checked)unlockAudio();updateHUD();};row.append(span,box);body.appendChild(row);}body.insertAdjacentHTML('beforeend','<p class="subheading">规则配置：标准260 / 练习180；出路预览是辅助。<br>表现配置：声音、粒子、震动、停顿独立可关；不改变反射角和入槽判定。</p>');action('返回菜单',()=>showPanel('menu'),true);}
 if(kind==='result'){const c=world.contract;$('panelTitle').textContent=c.status==='win'?'作业完成':'本次未完成';body.innerHTML='<p>'+c.reason+'。</p><div class="result-numbers"><div>入槽<b>'+c.delivered+' / 5</b></div><div>损失<b>'+c.lost+'</b></div><div>用时<b>'+c.elapsed.toFixed(1)+'秒</b></div></div><p>已改道的来件必须进入开口；撞到其他边缘也会损失。</p><p class="subheading">'+(world.mode==='practice'?'慢速练习 · 不记正式成绩':'正式作业 · 260速度')+' · 出路预览'+(settings.preview?'开':'关')+'<br>反馈：'+[settings.sound?'声音开':'静音',settings.reduced?'减少运动':settings.shake?'轻震开':'轻震关',settings.hitstop?'停顿开':'停顿关'].join(' / ')+'</p>';action('重玩这一局',()=>start(world.mode),true);action('换新配方',()=>start(world.mode,false));action('慢速练习',()=>start('practice'));history.push({mode:world.mode,recipe:world.recipe,status:c.status,delivered:c.delivered,lost:c.lost,elapsed:c.elapsed,settings:{...settings},commands:world.commands,events:world.events});if(history.length>6)history.shift();}
 if(kind==='tutorialDone'){ $('panelTitle').textContent='两次改道都完成了';body.innerHTML='<p>你用身体拉线，把不同入口的来件送进了上槽。</p><p>正式作业开启伤害：8件送入5件。来件每次只锁定一条直路，你可以先换位置，再看时机立锚。</p>';action('开始正式作业',()=>start('standard'),true);action('慢速练习',()=>start('practice'));action('重看教学',()=>restartTeaching());}
 if(kind==='tutorialFail'){ $('panelTitle').textContent='这件没有进入开口';body.innerHTML='<p>线接住后，来件沿接触时的角度走。瞄偏了就会撞到其他边缘。</p><p>再走到虚线圈，等来件靠近后立锚；拉线时看虚线出路是否朝向上槽。</p>';action('再试这个入口',()=>restartTeaching(tutorial.index),true);action('开始正式作业',()=>start('standard'));}
 if(kind==='diagnostic'){ $('panelTitle').textContent='检测已安全停止';body.innerHTML='<p>这一帧的碰撞计算没有收敛，作业没有继续计分。可重玩本局。</p>';action('重玩这一局',()=>start(world.mode),true);}
 $('panelActions').querySelector('button')?.focus({preventScroll:true});
}
function currentRecipe(){return tutorial?C.RECIPES[tutorial.index]:world.actors.find(a=>!a.dead&&!a.routed)?.recipe||world.recipe.sequence[Math.min(world.nextId,7)];}
function teaching(){if(!tutorial||overlayKind)return;const r=C.RECIPES[tutorial.index];if(tutorial.phase==='move'&&C.V.len(C.V.sub(world.p,r.anchor))<18&&C.V.len(world.velocity)<85){tutorial.phase='wait';world.spawn(r,180,1);tell('入口开始预警。先看尖楔的来路，别急着拉线。',3);}
 const a=world.actors.find(a=>!a.dead);if(tutorial.phase==='wait'&&a?.committed&&((tutorial.index===0&&a.p[0]>=r.cue)||(tutorial.index===1&&a.p[0]<=r.cue))){tutorial.phase='draw';if(tutorial.index===0){a.committed=false;a.launch=Infinity;tutorial.heldExample=true;}tell(tutorial.index===0?'示例来件在等你立锚：按住，然后向右上走。':'换了右入口。现在立锚，靠身体位置把它送进上槽。',4);}
 if(tutorial.heldExample&&world.line){tutorial.heldExample=false;a.launch=world.time;}
}
function processEvents(){for(;lastEvent<world.events.length;lastEvent++){const e=world.events[lastEvent];tone(e.type==='contract_end'&&e.status==='fail'?'contract_fail':e.type);if(['redirected','dock_delivered','player_hit'].includes(e.type)){fx.push({type:e.type,p:e.p,start:performance.now(),life:.7});if(e.type==='redirected'&&settings.hitstop)hitstop=.033;}
 if(e.type==='line_cancelled'){const msgs={expired:'线到期了：接近时再立锚，必须重新按一次。',too_long:'拉得太长，线已收回：缩短侧移距离，再按立锚。',released:'已收线。下次接近时，再按立锚。',consumed:'接住了！横条来件已经安全，等它进入开口。',hurt:'被尖楔撞到，线已收回。换位后重新立锚。'};if(msgs[e.reason])tell(msgs[e.reason],2.5);}
 if(e.type==='player_hit')tell('撞到尖楔，耐久 −1。已经改道的横条不会伤你。',3);
 if(e.type==='dock_delivered'){tell('送入'+e.dock+'，入槽 +1。接下来换个入口。',3);if(tutorial){if(tutorial.index===0){tutorial.index=1;tutorial.phase='move';tell('第一次入槽！现在走到第二个虚线圈，试试右入口。',5);}else showPanel('tutorialDone');}}
 if(e.type==='lost'){tell('撞到了槽口以外的边缘，损失 +1。试着调整线角度。',3);if(tutorial)showPanel('tutorialFail');}
 if(e.type==='warning'&&!tutorial)tell('下一件从'+currentRecipe().name+'进入。读来路，再找截击位置。',2);
 if(e.type==='contract_end'&&!tutorial&&!overlayKind)showPanel('result');}
 if(world.diagnostic&&!overlayKind)showPanel('diagnostic');}
function updateHUD(){if(!world)return;const c=world.contract,r=currentRecipe();$('mode').textContent=tutorial?'安全教学 · 不计成绩':world.mode==='practice'?'慢速练习 · 不记正式成绩':'正式作业 · 8件送入5件';$('progress').textContent=tutorial?'教学 '+c.delivered+' / 2':'入槽 '+c.delivered+' / 5';$('stock').textContent=tutorial?'无伤示例':'还剩 '+(8-c.settled.size)+'件';$('health').textContent=tutorial?'不受伤':'耐久 '+world.hp+' / 3';$('clock').textContent=tutorial?'无计时':'剩余 '+Math.max(0,Math.ceil(180-c.elapsed))+'秒';
 let instruction='';if(tutorial){$('stepLabel').textContent=tutorial.index?'换个入口':'先学一次';$('objective').textContent='正式作业要把8件中的5件送入槽。';if(tutorial.phase==='move')instruction=tutorial.index?'第一次已入槽。走到新的虚线圈，停一下。':'你是带缺口的卷线器。用方向键或摇杆走进虚线圈，停一下。';if(tutorial.phase==='wait')instruction='站在虚线圈附近，看入口的尖楔靠近；提示变成“立锚”时再按。';if(tutorial.phase==='draw')instruction=tutorial.index?'从右边来了：立锚后走动调角，让虚线出路朝向上方开口。':(settings.toggle?'按一下立锚，再向右上走到小圈；线会接住来件。':'按住立锚，向右上走到小圈，拉出一条线接住来件。');}else{$('stepLabel').textContent=world.mode==='practice'?'慢速练习':'当前作业';$('objective').textContent='8件送入5件 · 开口槽在上、下边缘';const a=world.actors.find(a=>!a.dead&&!a.routed);instruction=a?(a.committed?'尖楔正从'+r.name+'直走。等它靠近，再立锚并侧移，用虚线出路调角。':'下一件从'+r.name+'进入。先走位；来件接近时立锚，侧移拉线。'):'换位准备下一件。立锚后的侧移决定方向；把横条来件送入开口槽。';}
 $('instruction').textContent=instruction;let line='线待命 · 一条线接一件';if(world.line){const len=C.V.len(C.V.sub(world.p,world.line.a));line=len<C.TUNE.min?'线太短 · 再走远一点才生效':'线可接件 · 剩 '+Math.max(0,.9-world.time+world.line.start).toFixed(1)+'秒';}else if(world.state==='RECOVERY')line='正在回卷 · 很快可再立锚';else if(world.state==='HURT')line='受伤保护中 · 换位再立锚';$('lineInfo').textContent=line;$('anchor').textContent=settings.toggle?(world.held?'收线':'立锚'):'按住立锚';document.querySelector('.key-note span').textContent=settings.toggle?'再次按下收线 · Esc 暂停':'松开收线 · Esc 暂停';$('actionHint').textContent=settings.toggle?'按一下立锚，再按收线':'立锚后向旁边走，拉出短线';
 if(feedbackUntil<=world.time)$('feedback').textContent=world.line?(world.state==='DRAWING'?'当前线太短。继续侧移，实线才可以接件。':'虚线显示当前出路；它不会替你调整角度。'):(tutorial?'先移动，再立锚；教学不会扣耐久。':'尖楔有危险；改道后变横条，全程安全。');}
function fit(){const w=stage.clientWidth-4,h=stage.clientHeight-4,scale=Math.max(.01,Math.min(w/960,h/540)),dpr=Math.min(devicePixelRatio||1,3);canvas.style.width=960*scale+'px';canvas.style.height=540*scale+'px';canvas.width=Math.round(960*scale*dpr);canvas.height=Math.round(540*scale*dpr);draw();}
new ResizeObserver(fit).observe(stage);
function pathLine(a,b,color,width=2,dash=[]){ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function text(str,x,y,size=16,color='#344d46',align='left'){ctx.font='600 '+Math.max(size,11/(canvas.clientWidth/960))+'px system-ui, sans-serif';ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(str,x,y);}
function circle(p,r,fill,stroke=null){ctx.beginPath();ctx.arc(...p,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function arrow(a,b,color){pathLine(a,b,color,2,[6,5]);const angle=Math.atan2(b[1]-a[1],b[0]-a[0]);pathLine(b,[b[0]-12*Math.cos(angle-.5),b[1]-12*Math.sin(angle-.5)],color,2);pathLine(b,[b[0]-12*Math.cos(angle+.5),b[1]-12*Math.sin(angle+.5)],color,2);}
function draw(){if(!world||!canvas.width)return;ctx.setTransform(canvas.width/960,0,0,canvas.height/540,0,0);ctx.clearRect(0,0,960,540);ctx.fillStyle='#e9eade';ctx.fillRect(0,0,960,540);ctx.save();const pulse=fx.find(f=>f.type==='redirected'&&(performance.now()-f.start)<110);if(pulse&&settings.shake&&!settings.reduced)ctx.translate(Math.sin(performance.now()*.09),Math.cos(performance.now()*.07));
 ctx.fillStyle='#f7f6ed';ctx.fillRect(28,28,904,484);ctx.strokeStyle='#a7b3a3';ctx.lineWidth=3;ctx.strokeRect(28,28,904,484);ctx.globalAlpha=.45;for(let x=68;x<932;x+=40)for(let y=68;y<512;y+=40){circle([x,y],1.1,'#b9c4b1');}ctx.globalAlpha=1;
 for(let x=68;x<910;x+=20){pathLine([x,35],[x,x%40===28?45:41],'#c4ccb9',1);pathLine([x,499],[x,505],'#c4ccb9',1);}for(const p of [[15,15],[945,15],[15,525],[945,525]]){circle(p,5,'#cad0be','#98a28f');pathLine([p[0]-2,p[1]+2],[p[0]+2,p[1]-2],'#7d8d7b',1);}
 for(const d of C.DOCKS){const y=d.side==='top'?28:512,inside=d.side==='top'?1:-1;ctx.fillStyle='#27685a';ctx.fillRect(d.center-56,y-8,112,16);ctx.fillStyle='#c9d6bf';ctx.fillRect(d.center-56,y+inside*9-(inside<0?12:0),112,12);for(let x=d.center-45;x<d.center+55;x+=18)pathLine([x,y+inside*4],[x,y+inside*13],'#6b9472',3);text(d.label+' · 收件开口',d.center,y+inside*39,18,'#1d6656','center');}
 const r=currentRecipe();for(const inlet of C.RECIPES){const selected=inlet.id===r.id,at=inlet.entry,angle=Math.atan2(...[inlet.dir[1],inlet.dir[0]]);ctx.save();ctx.translate(...at);ctx.rotate(angle);ctx.fillStyle=selected?'#c76c44':'#b7bdae';ctx.fillRect(-13,-22,26,44);pathLine([-6,-13],[7,0],selected?'#693720':'#879682',3);pathLine([7,0],[-6,13],selected?'#693720':'#879682',3);ctx.restore();const off=at[0]<40?[42,-33]:at[0]>920?[-42,-33]:[0,-42];text(inlet.name,at[0]+off[0],at[1]+off[1],17,selected?'#a44d2e':'#72816f',at[0]>920?'right':'left');}
 for(const a of world.actors){if(a.dead)continue;if(!a.routed){const end=C.V.add(a.recipe.entry,C.V.mul(a.recipe.dir,a.recipe.id==='bottom'?484:904));pathLine(a.recipe.entry,end,a.committed?'#c381584d':'#b3513266',2,[9,9]);if(!a.committed&&Number.isFinite(a.launch)){const t=Math.max(0,Math.min(1,a.launch-world.time));ctx.strokeStyle='#b85b35';ctx.lineWidth=3;ctx.beginPath();ctx.arc(...a.p,25,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-t));ctx.stroke();}}
 if(a.routed&&!settings.reduced){const tail=C.V.sub(a.p,C.V.mul(a.v,.12));pathLine(tail,a.p,'#2f847580',5);}
 ctx.save();ctx.translate(...a.p);ctx.rotate(Math.atan2(a.v[1],a.v[0]));const actorScale=Math.max(1,14/(24*canvas.clientWidth/960));ctx.scale(actorScale,actorScale);ctx.fillStyle=a.routed?'#327c6c':'#b75735';ctx.strokeStyle=a.routed?'#174e48':'#783a28';ctx.lineWidth=2;ctx.beginPath();if(a.routed){ctx.rect(-10,-8,20,16);}else{ctx.moveTo(13,0);ctx.lineTo(-10,10);ctx.lineTo(-5,0);ctx.lineTo(-10,-10);ctx.closePath();}ctx.fill();ctx.stroke();if(a.routed){pathLine([-4,-7],[-4,7],'#f1f1d9',3);pathLine([4,-7],[4,7],'#f1f1d9',3);}ctx.restore();}
 if(tutorial){const tr=C.RECIPES[tutorial.index];if(tutorial.phase==='move'||tutorial.phase==='wait'){ctx.strokeStyle='#6a967e';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(...tr.anchor,21,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);text('先走到这里',tr.anchor[0],tr.anchor[1]+42,20,'#326d56','center');arrow(world.p,tr.anchor,'#699b7870');}if(tutorial.phase==='draw'&&tutorial.index===0){circle(tr.end,16,'#d7e1c65c');ctx.setLineDash([5,5]);ctx.strokeStyle='#63917b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(...tr.end,16,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);pathLine(tr.anchor,tr.end,'#739e794d',3,[6,5]);text('走到小圈',tr.end[0]+25,tr.end[1]-15,18,'#326d56');}}
 if(world.line){const a=world.line.a,b=world.p,len=C.V.len(C.V.sub(b,a)),active=len>=24,color=active?'#236e60':'#b78049';pathLine(a,b,'#f7f0d4',9);pathLine(a,b,color,5,active?[]:[5,4]);if(active){const t=C.V.mul(C.V.sub(b,a),1/len),n=[-t[1],t[0]];for(let k=12;k<len;k+=12){const p=C.V.add(a,C.V.mul(t,k));pathLine(C.V.sub(p,C.V.mul(n,3)),C.V.add(p,C.V.mul(n,3)),'#f5f0d1',1.5);}}ctx.save();ctx.translate(...a);ctx.rotate(Math.PI/4);ctx.fillStyle='#2b5148';ctx.fillRect(-6,-6,12,12);ctx.restore();if(settings.preview){const p=C.preview(a,b,r);if(p)arrow(p.p,p.end,'#3d8c75');}}
 ctx.save();ctx.translate(...world.p);const playerScale=Math.max(1,16/(32*canvas.clientWidth/960));ctx.scale(playerScale,playerScale);if(!settings.reduced)ctx.rotate(C.V.len(world.velocity)>5?Math.atan2(world.velocity[1],world.velocity[0]):-.5);circle([0,0],16,'#233e3b');circle([0,0],11,'#fbf4d6');circle([0,0],5,'#879a7d');ctx.fillStyle='#f7f6ed';ctx.fillRect(6,-4,13,8);pathLine([7,-6],[17,-6],'#233e3b',3);pathLine([7,6],[17,6],'#233e3b',3);ctx.restore();if(world.protectedUntil>world.time&&world.mode!=='tutorial'){ctx.strokeStyle='#b75735';ctx.lineWidth=2;ctx.beginPath();ctx.arc(...world.p,24,0,Math.PI*2);ctx.stroke();}
 if(tutorial&&tutorial.phase==='move')text('你 · 卷线器',world.p[0],world.p[1]+38,18,'#244e45','center');
 const now=performance.now();fx=fx.filter(f=>now-f.start<f.life*1000);for(const f of fx){const age=(now-f.start)/1000;ctx.globalAlpha=Math.max(0,1-age/f.life);ctx.strokeStyle=f.type==='player_hit'?'#b35132':'#287b66';ctx.lineWidth=2;ctx.beginPath();ctx.arc(...f.p,17+age*42,0,Math.PI*2);ctx.stroke();if(settings.particles&&!settings.reduced&&f.type==='redirected'){for(let i=0;i<7;i++){const th=i*2.4;circle([f.p[0]+Math.cos(th)*age*70,f.p[1]+Math.sin(th)*age*70],2,'#56816b');}}ctx.globalAlpha=1;}
 ctx.restore();
}
function keyMove(){let x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);return keys.size?[x,y]:pendingMove||joy;}
function loop(stamp){const elapsed=lastStamp?Math.min(.1,(stamp-lastStamp)/1000):0;lastStamp=stamp;if(armed&&!world.paused&&world.contract.status==='active'){if(hitstop>0)hitstop=Math.max(0,hitstop-elapsed);else{accum+=elapsed;let count=0;while(accum>=C.TUNE.dt&&count++<6&&!world.paused){world.step({move:keyMove(),press,release,toggle:settings.toggle});press=release=false;pendingMove=null;accum-=C.TUNE.dt;teaching();processEvents();}}}else accum=0;updateHUD();draw();requestAnimationFrame(loop);}
const movement=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'];
game.addEventListener('keydown',e=>{if(scrollY>8)return;if(e.target.matches('input,select,textarea'))return;if(e.code==='Escape'){e.preventDefault();if(overlayKind==='pause'){hidePanel();focusGame();}else if(!overlayKind)pause();else if(!['result','tutorialDone','tutorialFail','diagnostic'].includes(overlayKind)){hidePanel();focusGame();}return;}if(overlayKind)return;if(e.target.closest('button')&&e.target!==$('anchor'))return;if(movement.includes(e.code)||e.code==='Space'){e.preventDefault();armed=true;unlockAudio();if(e.repeat)return;if(e.code==='Space'){if(settings.toggle||(!spaceHeld&&!anchorPointers.size))press=true;spaceHeld=true;$('anchor').classList.add('pressed');}else{keys.add(e.code);pendingMove=keyMove();}}});
game.addEventListener('keyup',e=>{if(overlayKind||e.target.matches('input,select,textarea')||(e.target.closest('button')&&e.target!==$('anchor')))return;if(movement.includes(e.code)){keys.delete(e.code);e.preventDefault();}if(e.code==='Space'&&!e.target.matches('input,select,textarea')){spaceHeld=false;if(!anchorPointers.size)release=true;$('anchor').classList.remove('pressed');e.preventDefault();}});
function beginAnchor(e){if(e.button&&e.button!==0)return;if(overlayKind||world.paused)return;e.preventDefault();focusGame();unlockAudio();e.currentTarget.setPointerCapture(e.pointerId);if(!anchorPointers.size&&(settings.toggle||!spaceHeld)){press=true;$('anchor').classList.add('pressed');}anchorPointers.add(e.pointerId);}
function endAnchor(e){if(!anchorPointers.has(e.pointerId))return;anchorPointers.delete(e.pointerId);if(!anchorPointers.size&&!spaceHeld){release=true;$('anchor').classList.remove('pressed');}}
for(const target of [canvas,$('anchor')]){target.addEventListener('pointerdown',beginAnchor);target.addEventListener('pointerup',endAnchor);target.addEventListener('pointercancel',()=>{clearInput();});target.addEventListener('lostpointercapture',endAnchor);target.addEventListener('contextmenu',e=>e.preventDefault());}
$('anchor').addEventListener('click',e=>e.preventDefault());
function moveJoy(e){if(e.pointerId!==joyPointer)return;const dx=e.clientX-joyOrigin[0],dy=e.clientY-joyOrigin[1],l=Math.hypot(dx,dy),rad=$('joystick').clientWidth*.35,m=Math.min(1,l/rad);joy=l<4?[0,0]:[dx/l*m,dy/l*m];$('stick').style.transform='translate('+joy[0]*rad+'px,'+joy[1]*rad+'px)';}
$('joystick').addEventListener('pointerdown',e=>{if(overlayKind||joyPointer!==null)return;e.preventDefault();focusGame();unlockAudio();joyPointer=e.pointerId;joyOrigin=[e.clientX,e.clientY];$('joystick').setPointerCapture(e.pointerId);moveJoy(e);});$('joystick').addEventListener('pointermove',moveJoy);for(const evt of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(evt,e=>{if(e.pointerId===joyPointer){joyPointer=null;joyOrigin=null;joy=[0,0];$('stick').style.transform='';}});
$('pause').onclick=()=>pause();$('menu').onclick=()=>{world.setPause(true);showPanel('menu');};$('closePanel').onclick=()=>{hidePanel();focusGame();};
window.addEventListener('blur',()=>{if(armed)pause('窗口失去焦点');else clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&armed)pause('页面切到后台');});window.addEventListener('scroll',()=>{if(scrollY>8){if(armed)pause('你正在阅读玩法');clearInput();if(game.contains(document.activeElement))$('how').focus({preventScroll:true});}},{passive:true});game.addEventListener('focusout',e=>{if(e.relatedTarget&&!game.contains(e.relatedTarget)&&armed)pause('操作焦点离开作业台');});
// Debug evidence is read-only to callers: no setters, teleport or automatic play.
Object.defineProperty(window,'TURNLINE_INSPECT',{value:()=>({recipe:world.recipe,mode:world.mode,p:[...world.p],tick:world.tick,time:world.time,paused:world.paused,line:world.line,state:world.state,hp:world.hp,contract:{...world.contract,settled:[...world.contract.settled]},events:world.events.slice(-30),tutorial,settings:{...settings},actors:world.actors.map(a=>({id:a.id,p:[...a.p],v:[...a.v],routed:a.routed,committed:a.committed})),commands:world.commands.slice(-8),diagnostic:world.diagnostic}),writable:false});
start('tutorial');armed=false;fit();requestAnimationFrame(loop);
})();
