(function(){
'use strict';
const $=s=>document.querySelector(s), BX=window.BX,R=BX.R,game=$('#game'),canvas=$('#arena'),ctx=canvas.getContext('2d');
const STORE='bengxian1910';let storageOK=true;
function load(k,f){try{const x=JSON.parse(localStorage.getItem(STORE+'.'+k));return x===null?f:x;}catch{storageOK=false;return f;}}
function save(k,x){try{localStorage.setItem(STORE+'.'+k,JSON.stringify(x));}catch{storageOK=false;}}
const defaults={assist:false,toggle:false,mute:false,volume:.5,music:.08,reduce:matchMedia('(prefers-reduced-motion: reduce)').matches,log:false,large:false,binds:{up:['KeyW','ArrowUp'],down:['KeyS','ArrowDown'],left:['KeyA','ArrowLeft'],right:['KeyD','ArrowRight'],main:['Space','KeyJ'],precision:['ShiftLeft','ShiftRight']}};
let settings=load('settings',defaults);if(!settings||typeof settings!=='object')settings={...defaults};settings={...defaults,...settings};
if(!settings.binds||!Object.keys(defaults.binds).every(k=>Array.isArray(settings.binds[k])&&settings.binds[k].length&&settings.binds[k].every(x=>typeof x==='string'&&/^[A-Za-z0-9]+$/.test(x))))settings.binds=defaults.binds;
settings.binds=Object.fromEntries(Object.keys(defaults.binds).map(k=>[k,settings.binds[k].slice()]));
for(const k of ['assist','toggle','mute','reduce','log','large'])if(typeof settings[k]!=='boolean')settings[k]=defaults[k];
for(const k of ['volume','music'])settings[k]=Number.isFinite(Number(settings[k]))?Math.max(0,Math.min(1,Number(settings[k]))):defaults[k];
let sim=new BX.Game(),menu='welcome',returnMenu=null,scale=1,fx=[],recallTrail=[],toastUntil=0,feedbackMessage='',runningFocused=true;
let keys=new Set(),touchMain=false,padMain=false,rawMain=false,logicalMain=false,press=false,release=false,touchPrecision=false;
let stick={x:0,y:0,id:null},mainPointer=null,precisionPointer=null,padVector={x:0,y:0},padPrecision=false,usedPad=null,padConfirmHeld=false,padPrev=[],menuIndex=0,lastMenuNav=0;
let bindWaiting=null,record=null,lastRecord=load('log',null),best=load('best',{}),acc=0,lastFrame=performance.now(),shownResult=false,displayScore=0,latestBank=null;
if(!best||typeof best!=='object'||Array.isArray(best))best={};
best=Object.fromEntries(Object.entries(best).filter(([,x])=>x&&Number.isSafeInteger(x.score)&&x.score>=0&&Number.isInteger(x.seed)&&x.seed>=0&&x.seed<=2147483647));
const frameSamples=[],stepSamples=[];let elapsedFrame=0;
class Sound{
 constructor(){this.ctx=null;this.captureLast=-1000;this.voices=[];this.dangerUntil=0;}
 unlock(){try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();const c=this.ctx;this.master=c.createGain();this.master.gain.value=settings.mute?0:settings.volume*.55;this.limiter=c.createDynamicsCompressor();this.limiter.threshold.value=-8;this.limiter.knee.value=4;this.limiter.ratio.value=12;this.limiter.attack.value=.003;this.limiter.release.value=.1;this.master.connect(this.limiter);this.limiter.connect(c.destination);this.normal=c.createGain();this.normal.connect(this.master);this.danger=c.createGain();this.danger.connect(this.master);this.music=c.createGain();this.music.connect(this.master);this.music.gain.value=settings.music*.1;for(const f of [110,164.81]){const o=c.createOscillator();o.frequency.value=f;o.type='sine';o.connect(this.music);o.start();}}if(this.ctx.state==='suspended')this.ctx.resume();}catch{}}
 update(){if(this.ctx){this.master.gain.setTargetAtTime(settings.mute?0:settings.volume*.55,this.ctx.currentTime,.02);this.music.gain.setTargetAtTime(menu||sim.state==='PAUSED'?0:settings.music*.1,this.ctx.currentTime,.1);}}
 play(type,n=1){if(!this.ctx||settings.mute)return;const c=this.ctx,t=c.currentTime,danger=['hit','cut','warning','run_end'].includes(type);
  if(type==='capture'){if(t-this.captureLast<.035||this.voices.filter(x=>x>t).length>=6)return;this.captureLast=t;this.voices.push(t+.07);this.voices=this.voices.filter(x=>x>t);}
  if(danger){this.dangerUntil=t+.18;this.normal.gain.cancelScheduledValues(t);this.normal.gain.setTargetAtTime(.5,t,.013);this.normal.gain.setTargetAtTime(1,t+.18,.02);}
  const profiles={deploy:[330,500,.07,'triangle'],capture:[640+sim.cargo.length*24,840,.065,'sine'],full:[850,1050,.12,'triangle'],recall_begin:[740,240,.11,'triangle'],bank:[420,800,.14,'sine'],cut:[175,65,.12,'sawtooth'],hit:[90,42,.18,'square'],run_end:[300,90,.3,'triangle'],warning:[900,500,.16,'square']};const p=profiles[type];if(!p)return;
  const tone=(f,to,d,w,vol)=>{const o=c.createOscillator(),g=c.createGain();o.type=w;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(to,t+d);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(danger?this.danger:this.normal);o.start(t);o.stop(t+d+.01);o.onended=()=>{o.disconnect();g.disconnect();};};tone(...p,danger?.2:.2);if(type==='bank'&&n>=8)tone(90,55,.18,'sine',.18);
 }
}
const sound=new Sound();
function resize(){const b=$('#stage').getBoundingClientRect();const w=Math.max(1,Math.min(b.width,b.height*1280/720)),h=w*720/1280;scale=w/1280;canvas.style.width=w+'px';canvas.style.height=h+'px';const dpr=Math.min(devicePixelRatio||1,3);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(canvas.width/1280,0,0,canvas.height/720,0,0);}
new ResizeObserver(resize).observe($('#stage'));window.addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);
function feedback(message,color='var(--line)'){feedbackMessage=message;toastUntil=performance.now()+1700;$('#feedback').textContent=message;$('#feedback').style.color=color;}
function mainRaw(){return [...keys].some(k=>settings.binds.main.includes(k))||touchMain||padMain;}
function syncMain(){const next=mainRaw();if(next===rawMain)return;const down=next;rawMain=next;
 if(menu||sim.state==='PAUSED'){if(!down&&!settings.toggle){sim.pausedRelease();logicalMain=false;if(menu==='pause')showPause();}return;}
 if(settings.toggle){if(down){logicalMain=!logicalMain;if(logicalMain)press=true;else release=true;}}
 else{logicalMain=next;if(next)press=true;else release=true;}
}
function clearInput(defer=false){if(defer&&!settings.toggle&&rawMain)sim.pausedRelease();keys.clear();touchMain=padMain=rawMain=false;press=release=false;touchPrecision=false;padPrecision=false;stick={x:0,y:0,id:null};mainPointer=precisionPointer=null;padVector={x:0,y:0};if(!settings.toggle)logicalMain=false;$('#joystick .stick').style.transform='';}
function device(name){if(record&&!record.devices.includes(name))record.devices.push(name);}
function focusGame(){game.focus({preventScroll:true});runningFocused=true;sound.unlock();}
function input(){const active=k=>settings.binds[k].some(c=>keys.has(c));let x=(active('right')?1:0)-(active('left')?1:0)+stick.x+padVector.x,y=(active('down')?1:0)-(active('up')?1:0)+stick.y+padVector.y;const i={x,y,precision:active('precision')||touchPrecision||padPrecision,press,release};press=release=false;return i;}
function begin(practice=false,seed=sim.seed){clearInput();logicalMain=false;sim=new BX.Game(seed,settings.assist?'assist':'standard',practice);fx=[];recallTrail=[];shownResult=false;displayScore=0;latestBank=null;hidePanel();focusGame();lastFrame=performance.now();acc=0;
 record=settings.log?{build:BX.BUILD,rules:R.rules_version,seed:sim.seed,mode:sim.mode,practice,initialWaves:sim.waves.map(e=>({...e})),inputs:[],events:[],devices:[],samples:[],startedAt:new Date().toISOString()}:null;
 feedback(practice?'先按住布线，再向右移动。':'按住布线并移动，线拉开后才接弹。');consume();updateHUD();}
function newSeed(){const a=new Uint32Array(1);try{crypto.getRandomValues(a);return a[0]&0x7fffffff;}catch{return Math.floor(Math.random()*2147483648);}}
function pause(reason='主动暂停',clear=false){if(menu==='welcome'||menu==='results'||menu==='tutorialDone')return;sim.pause(reason);if(clear)clearInput(true);press=release=false;showPause();acc=0;sound.update();}
function resume(){press=release=false;sim.resume();hidePanel();focusGame();acc=0;lastFrame=performance.now();}
function hidePanel(){menu=null;$('#overlay').hidden=true;bindWaiting=null;sound.update();}
function panel(kind,title,body,buttons,back=null){menu=kind;bindWaiting=null;$('#overlay').hidden=false;$('#panelTitle').textContent=title;$('#panelBody').innerHTML=body;$('#panelActions').replaceChildren();$('#panelBack').hidden=!back;$('#panelBack').onclick=back;for(const b of buttons){const el=document.createElement('button');el.textContent=b.text;if(b.primary)el.className='primary';el.onclick=()=>{sound.unlock();b.action();};$('#panelActions').append(el);}menuIndex=0;$('#panelBody').scrollTop=0;sound.update();updateHUD();}
function welcome(){panel('welcome','绷线',`<p class="tag">接住一串，再回到你留下的地方</p><p class="lead">撑过 180 秒，接弹收线得分。</p><p>按住「布线」留下锚点，再移动白色身体拉线。接住圆弹后松手，回到锚点才计分。</p><p>先用三个动作练习一次，或直接进入挑战。</p><div class="legend"><span>◆ 白色：你</span><span>◇ 青绿：锚点 / 货物</span><span>● 琥珀：可接圆弹</span><span>◀ 珊瑚：切线针</span></div>`,[{text:'先练一次',primary:true,action:()=>begin(true)},{text:'直接挑战',action:()=>begin(false)}]);}
function showPause(){panel('pause','已暂停',`<p>${sim.pauseReason}。局面与时间已保留。</p><p class="lead">${sim.pendingRelease?'恢复后将收回当前线。':'继续后从当前局面接着玩。'}</p><p>空线只撤线，有货才回到锚点。恢复由你明确确认。</p>`,[{text:sim.pendingRelease?'继续并收线':'继续游戏',primary:true,action:resume},{text:'重玩这一局',action:()=>begin(sim.practice)},{text:'回到开始',action:welcome}]);}
function results(){if(record){record.final=sim.snapshot();record.expandedWaves=sim.waves.map(e=>({...e}));lastRecord=record;save('log',record);}if(!sim.practice){const k=R.rules_version+'.'+sim.mode;if(!best||typeof best!=='object')best={};if(sim.score>(best[k]?.score??-1)){best[k]={score:sim.score,seed:sim.seed};save('best',best);}save('seed',sim.seed);}
 panel('results',sim.hp===0?'挑战中断':'挑战完成',`<p>${sim.reason}。${sim.hp===0?'圆弹和针碰到身体都会扣命。可以试着提前收线。':'最后未开始收回的货物不计分。'}</p><div class="result-score">${sim.score} <span style="font-size:18px">分</span></div><div class="result-grid"><div><span>最大单串</span><b>${sim.stats.maxString} 颗</b></div><div><span>成功收线</span><b>${sim.stats.banks} 次</b></div><div><span>断线损失</span><b>${sim.stats.cutLoss} 颗</b></div></div><p class="meta">局面 ${sim.seed} · ${sim.mode==='assist'?'辅助慢速':'标准'} · 规则 ${R.rules_version}<br>本机同模式最佳 ${best[R.rules_version+'.'+sim.mode]?.score||0} 分 · 局面 ${best[R.rules_version+'.'+sim.mode]?.seed??sim.seed}</p>`,[{text:'重玩这一局',primary:true,action:()=>begin(false)},{text:'换个局面',action:()=>begin(false,newSeed())}]);clearInput();logicalMain=false;}
function settingsPanel(){returnMenu=menu||'pause';if(!menu){sim.pause('打开设置');clearInput(true);}const flag=(k,label)=>`<div class="setting-row"><label for="set-${k}">${label}</label><input id="set-${k}" type="checkbox" ${settings[k]?'checked':''}></div>`;
 panel('settings','设置',`${flag('assist','辅助慢速（世界速度 0.8；新一局生效）')}${flag('toggle','切换布线（点一次放锚，再点一次收线）')}${flag('mute','静音')}${flag('reduce','减少装饰运动')}${flag('large','加大界面文字')}<div class="setting-row"><label for="volume">音效音量</label><input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></div><div class="setting-row"><label for="music">底层音量</label><input id="music" type="range" min="0" max="1" step=".05" value="${settings.music}"></div>${flag('log','自愿记录本地试玩日志（下一局生效）')}<p class="meta">记录输入、展开波次与事件；仅保存在本机，不会上传。</p><div class="setting-row"><label>本地记录</label><button id="export">导出日志</button><button id="deleteLog">删除</button></div><p>键盘重绑定：选择动作后按新键。Esc 始终用于暂停；默认 Space 与 J 合用。</p><div class="bind-list">${Object.keys(defaults.binds).map(k=>`<button data-bind="${k}">${{up:'向上',down:'向下',left:'向左',right:'向右',main:'布线 / 收线',precision:'精确移动'}[k]} · ${settings.binds[k].map(keyName).join(' / ')}</button>`).join('')}</div><div class="setting-row"><button id="resetKeys">恢复默认按键</button><button id="review">重看教学</button></div><p id="settingNote" class="panelBody-note"></p><div class="legend"><span>白色梭形：身体，亮点是核心</span><span>青绿菱形：锚点 / 暂存</span><span>琥珀圆形：普通弹</span><span>珊瑚尖形 + 虚线预告：切线针</span></div><p class="meta">${storageOK?'设置自动保存在本机。':'浏览器存储不可用；仍可游玩，本次设置暂存。'}<br>手柄：左摇杆移动，A / RB 布线，LB 精确；Start 暂停。菜单用方向选择、A 确认、B 返回。</p>`,[{text:'返回',primary:true,action:closeSettings}],closeSettings);
 for(const k of ['assist','toggle','mute','reduce','log','large'])$('#set-'+k).onchange=e=>{settings[k]=e.target.checked;if(k==='toggle'){clearInput();logicalMain=['OPEN','FULL'].includes(sim.action);}applySettings();};
 for(const k of ['volume','music'])$('#'+k).oninput=e=>{settings[k]=Number(e.target.value);sound.unlock();applySettings();};
 document.querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>{bindWaiting=b.dataset.bind;$('#settingNote').textContent='请按新键；Esc 取消。';});
 $('#resetKeys').onclick=()=>{settings.binds=structuredClone(defaults.binds);applySettings();settingsPanelRefresh();};$('#review').onclick=()=>begin(true);
 $('#export').onclick=()=>{const rec=record||lastRecord;if(!rec){$('#settingNote').textContent='尚无日志。勾选后开始新一局。';return;}const blob=new Blob([JSON.stringify({...rec,final:record?sim.snapshot():rec.final,expandedWaves:record?sim.waves:rec.expandedWaves,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bengxian1910-'+rec.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#settingNote').textContent='已导出本地匿名记录。';};
 $('#deleteLog').onclick=()=>{record=lastRecord=null;try{localStorage.removeItem(STORE+'.log');}catch{}$('#settingNote').textContent='本地日志已删除。';};
}
function settingsPanelRefresh(){const ret=returnMenu;settingsPanel();returnMenu=ret;}
function closeSettings(){bindWaiting=null;applySettings();if(returnMenu==='welcome')welcome();else if(returnMenu==='results')results();else if(returnMenu==='tutorialDone')tutorialDone();else showPause();}
function applySettings(){save('settings',settings);game.classList.toggle('large-ui',settings.large);$('#keyLabel').textContent=settings.binds.main.map(keyName).join(' / ');$('.desktop-help kbd').textContent=['up','left','down','right'].map(k=>settings.binds[k].map(keyName).join('/')).join(' ');sound.update();updateHUD();}
function keyName(code){return ({Space:'空格',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',ShiftLeft:'左 Shift',ShiftRight:'右 Shift'})[code]||code.replace(/^Key|^Digit/,'');}
function tutorialDone(){panel('tutorialDone','已经会收一串了',`<p class="lead">${sim.tutorial.needleDone?'你已经见过切线针。':'针的预告出现后，你赶在它前面收回了货物。'}</p><p>${sim.tutorial.doneReason||'接弹先暂存，收回到锚点才计分；针碰线会丢掉暂存。'}</p><p>练习的分数不带进正式挑战。正式局只有 3 条生命，持续 180 秒。</p>`,[{text:'开始正式挑战',primary:true,action:()=>begin(false)},{text:'再练一次',action:()=>begin(true)}]);clearInput();logicalMain=false;}
function consume(){for(const e of sim.drain()){
 if(record)record.events.push(e);sound.play(e.type,e.count||1);
 if(e.type==='capture')fx.push({kind:'capture',p:e.at,time:performance.now(),duration:70});
 if(e.type==='bank'){latestBank={from:displayScore,to:sim.score,time:performance.now()};fx.push({kind:'bank',p:e.anchor,time:performance.now(),duration:120});feedback(`收回 ${e.count} 颗，+${e.points} 分`);}
 if(e.type==='cut'){fx.push({kind:'cut',a:e.a,p:e.p,time:performance.now(),duration:120});feedback(`线被针切断 · 丢失 ${e.lost} 颗，生命未减少`,'var(--red)');logicalMain=false;}
 if(e.type==='hit'){fx.push({kind:'hit',p:e.pos,time:performance.now(),duration:120});feedback(e.practice?'身体碰弹了，练习不扣命；重新拉线再试。':'身体碰弹 · 已掉 1 条生命，暂存清空','var(--red)');logicalMain=false;}
 if(e.type==='full')feedback('12/12 已满 · 圆弹会穿过，请收线');
 if(e.type==='empty_release')feedback('空线撤回 · 留在原地，没有保护');
 if(e.type==='blocked')feedback(e.reason);
 if(e.type==='tutorial_done'){sim.tutorial.doneReason=e.reason;tutorialDone();}
 if(e.type==='run_end'&&!shownResult){shownResult=true;results();}
 }
 if(fx.length>128)fx.splice(0,fx.length-128);
}
const phases=['接住','换角','及时收','处理交叉','连续取舍','综合压力'];
function updateHUD(){const t=sim.tutorial,remaining=Math.max(0,Math.ceil((108000-sim.clock)/600));$('#mode').textContent=sim.practice?'行动练习 · 不计正式成绩':sim.mode==='assist'?'辅助慢速挑战':'标准挑战';$('#time').textContent=sim.practice?`第 ${t.step}/3 步`:remaining<=6?`最后收线 ${remaining} 秒`:`剩余 ${remaining} 秒`;$('#hp').textContent=sim.practice?'练习':Array.from({length:3},(_,i)=>i<sim.hp?'●':'○').join(' ');$('#score').textContent=Math.round(displayScore)+' 分';$('#cargo').innerHTML=`<span>${sim.cargo.length}/12</span> <span class="cargo-points">可收 ${BX.score(sim.cargo.length)} 分</span>`;
 let hint,phase;if(sim.practice){phase=['','1 · 拉出一根线','2 · 接三颗，再收回','3 · 认出切线针'][t.step];if(t.needsCenter)hint='这里放不下教学来弹。撤线后移到场地中央，再拉线。';else if(t.step===1)hint='按住「布线」，向右移动白色身体，把线拉到 120。';else if(t.step===2)hint=sim.cargo.length?'圆弹已变成线上菱珠。松开布线，回到锚点才入账。':'稳住青绿线，让三颗琥珀圆弹碰到线；身体避开它们。';else hint=t.needle?'珊瑚虚线是针的预告。现在松手收回；针碰线会丢货。':'再按住布线并移动，接住圆弹；随后看针的虚线预告。';}
 else{phase=sim.clock>=104400?'最后一串':`${Math.min(6,Math.floor(sim.clock/18000)+1)}/6 · ${phases[Math.min(5,Math.floor(sim.clock/18000))]}`;
 if(sim.action==='RECALL')hint='正在回到菱形锚点。到达才计分，沿路清弹不加分。';else if(sim.action==='FULL')hint='线已满，圆弹会穿过；松手收回 12 颗，避免针切断。';else if(sim.cargo.length)hint='菱珠是暂存货物。松手回到锚点入账，也可以继续移动接弹。';else if(sim.action==='OPEN')hint=sim.anchor&&Math.hypot(sim.pos.x-sim.anchor.x,sim.pos.y-sim.anchor.y)<48?'线太短，虚线还不能接弹。继续移动，拉开身体与锚点。':'青绿实线能接圆弹；珊瑚尖针会切线，身体也要躲弹。';else hint='按住布线留下锚点，再移动身体拉线；接到货物后松手收回。';}
 if(sim.state==='PAUSED')hint=sim.pendingRelease?'已暂停 · 明确继续后，才执行待收线动作。':'已暂停 · 阅读或失焦不会自动继续。';$('#phase').textContent=phase||'接住 → 收回';$('#hint').textContent=hint;
 const main=$('#mainAction');main.classList.toggle('held',logicalMain&&!menu);main.innerHTML=settings.toggle?((['OPEN','FULL'].includes(sim.action)?'点一下收回':'点一下布线')+'<br><small>再次点击切换</small>'):'按住布线<br><small>松手收回</small>';main.disabled=!!menu;$('#skip').hidden=!sim.practice||!!menu;$('#precision').disabled=!!menu;$('#precision').classList.toggle('held',touchPrecision||padPrecision||settings.binds.precision.some(k=>keys.has(k)));$('#pause').textContent=sim.state==='PAUSED'?'已暂停':'暂停';$('#feedback').classList.toggle('on',performance.now()<toastUntil&&!menu);}
function diamond(p,r,fill,stroke){ctx.beginPath();ctx.moveTo(p.x,p.y-r);ctx.lineTo(p.x+r,p.y);ctx.lineTo(p.x,p.y+r);ctx.lineTo(p.x-r,p.y);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function line(a,b,color,width=1,dash=[]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}
function circle(p,r,color,width=1,fill=false){ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);if(fill){ctx.fillStyle=color;ctx.fill();}else{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}}
function draw(){const now=performance.now(),s=sim;ctx.clearRect(0,0,1280,720);ctx.fillStyle='#101820';ctx.fillRect(0,0,1280,720);ctx.strokeStyle='#223540';ctx.lineWidth=1;for(let x=128;x<=1152;x+=64)line({x,y:112},{x,y:608},'#20313b');for(let y=112;y<=608;y+=62)line({x:128,y},{x:1152,y},'#20313b');ctx.strokeStyle='#526673';ctx.lineWidth=2;ctx.strokeRect(128,112,1024,496);
 for(const [edge,ports] of Object.entries(R.ports))for(let i=0;i<3;i++){const p={x:ports[i][0],y:ports[i][1]},vert=edge==='N'||edge==='S';line({x:p.x-(vert?12:0),y:p.y-(vert?0:12)},{x:p.x+(vert?12:0),y:p.y+(vert?0:12)},'#677f8e',3);}
 for(const e of s.waves){if(!s.practice&&e.warned&&s.clock<e.fire_clock){const p={x:R.ports[e.edge][e.lane][0],y:R.ports[e.edge][e.lane][1]},color=e.kind==='CUTTER'?'#ff6a6a':'#f4d35e';circle(p,13+7*Math.max(0,(e.fire_clock-s.clock)/450),color,2);if(e.kind==='CUTTER'&&e.locked_target){const q=e.locked_target,dx=q.x-p.x,dy=q.y-p.y,l=Math.hypot(dx,dy)||1;line(p,{x:p.x+dx/l*1400,y:p.y+dy/l*1400},'#ff6a6aaa',Math.max(1,.7/scale),[8,9]);diamond(p,5,null,color);}}}
 const needle=s.tutorial.needle;if(s.practice&&needle&&s.clock<needle.fire){line(needle.p,{x:needle.p.x+needle.dir.x*440,y:needle.p.y+needle.dir.y*440},'#ff6a6aaa',Math.max(1,.7/scale),[8,9]);diamond(needle.p,12,null,'#ff6a6a');}
 if(s.anchor){const l=Math.hypot(s.pos.x-s.anchor.x,s.pos.y-s.anchor.y),valid=l>=48;
  if(['OPEN','FULL'].includes(s.action)){if(s.action==='FULL'){const nx=-(s.pos.y-s.anchor.y)/(l||1)*3,ny=(s.pos.x-s.anchor.x)/(l||1)*3;for(const sign of [-1,1])line({x:s.anchor.x+nx*sign,y:s.anchor.y+ny*sign},{x:s.pos.x+nx*sign,y:s.pos.y+ny*sign},'#63d7c5',Math.max(1.5,.8/scale));}else{line(s.anchor,s.pos,'#63d7c525',10);line(s.anchor,s.pos,valid?'#63d7c5':'#7d8b99',valid?Math.max(4,1.5/scale):2,valid?[]:[8,8]);}}
  if(s.action==='RECALL')circle(s.pos,17,'#63d7c5',2);
  ctx.lineWidth=Math.max(2,1/scale);diamond(s.anchor,Math.max(10,4/scale),s.cargo.length?'#63d7c5':null,'#63d7c5');circle(s.anchor,20,'#63d7c52f',1);
 }
 recallTrail=recallTrail.filter(p=>now-p.time<=100);if(s.action==='RECALL'&&!settings.reduce)recallTrail.push({x:s.pos.x,y:s.pos.y,time:now});if(!settings.reduce)for(let i=1;i<recallTrail.length;i++){ctx.globalAlpha=.35*(1-(now-recallTrail[i].time)/100);line(recallTrail[i-1],recallTrail[i],'#63d7c5',12);}ctx.globalAlpha=1;
 for(const b of s.bullets){if(b.type==='NORMAL'){circle(b,Math.max(7,2.6/scale),'#f4d35e',1,true);circle(b,3,'#ffeab0',1,true);}else{ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vy,b.vx));const k=Math.max(1,3/scale/9);ctx.scale(k,k);ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(-8,-5);ctx.lineTo(-5,0);ctx.lineTo(-8,5);ctx.closePath();ctx.fillStyle='#ff6a6a';ctx.fill();line({x:-11,y:-4},{x:-11,y:4},'#ff6a6a',1.5);line({x:-14,y:-3},{x:-14,y:3},'#ff6a6a',1.5);ctx.restore();}}
 if(s.anchor)for(let i=0;i<s.cargo.length;i++){const l=Math.hypot(s.pos.x-s.anchor.x,s.pos.y-s.anchor.y)||1,spacing=Math.min(.85/Math.max(1,s.cargo.length-1),Math.max(12,5/scale)/l),center=s.cargo.reduce((a,b)=>a+b,0)/s.cargo.length;let u=Math.max(.075,Math.min(.925-spacing*(s.cargo.length-1),center-spacing*(s.cargo.length-1)/2))+i*spacing;if(s.action==='RECALL')u*=Math.max(0,1-s.recall.elapsed/s.recall.ticks);const p={x:s.anchor.x+(s.pos.x-s.anchor.x)*u,y:s.anchor.y+(s.pos.y-s.anchor.y)*u};diamond(p,Math.max(5,2.2/scale),'#63d7c5','#101820');}
 fx=fx.filter(f=>now-f.time<f.duration);for(const f of fx){const q=(now-f.time)/f.duration;ctx.globalAlpha=1-q;if(f.kind==='capture')circle(f.p,8+q*14,'#63d7c5',3);if(f.kind==='bank')circle(f.p,8+q*32,'#63d7c5',3);if(f.kind==='hit')circle(f.p,20+q*18,'#ff6a6a',3);if(f.kind==='cut'){const m={x:(f.a.x+f.p.x)/2,y:(f.a.y+f.p.y)/2};line(f.a,{x:m.x+(f.a.x-m.x)*q,y:m.y+(f.a.y-m.y)*q},'#ff6a6a',3);line(f.p,{x:m.x+(f.p.x-m.x)*q,y:m.y+(f.p.y-m.y)*q},'#ff6a6a',3);}ctx.globalAlpha=1;}
 if(s.tick<s.invulnerable)circle(s.pos,Math.max(18,6/scale),'#f7fbff80',2);
 ctx.save();ctx.translate(s.pos.x,s.pos.y);const vis=Math.max(1,4/scale/11);ctx.scale(vis,vis);ctx.beginPath();ctx.moveTo(0,-11);ctx.quadraticCurveTo(12,0,0,11);ctx.quadraticCurveTo(-12,0,0,-11);ctx.fillStyle='#f7fbff';ctx.fill();ctx.restore();circle(s.pos,6,'#f7fbff',1,true);circle(s.pos,6,'#101820',Math.max(1,.6/scale));
 // On narrow views, near-body numbers live in the readable DOM HUD.
 if(scale>.55&&s.anchor){ctx.font='18px system-ui';ctx.textAlign='center';ctx.fillStyle='#63d7c5';ctx.fillText(s.action==='FULL'?'12/12 · 已满':`${s.cargo.length}/12`,s.pos.x,s.pos.y-27);ctx.fillStyle='#a8c5c1';ctx.font='16px system-ui';ctx.fillText(s.cargo.length?'回到这里':'锚点',s.anchor.x,s.anchor.y+35);}
}
$('#pause').onclick=()=>{sound.unlock();if(!menu)pause();else if(menu==='pause')resume();};$('#settings').onclick=()=>{sound.unlock();if(menu==='settings')closeSettings();else settingsPanel();};
$('#skip').onclick=()=>begin(false);
game.addEventListener('pointerdown',e=>{if(e.target===canvas||e.target===game)focusGame();});
const main=$('#mainAction');main.addEventListener('pointerdown',e=>{if(menu)return;e.preventDefault();focusGame();main.setPointerCapture(e.pointerId);mainPointer=e.pointerId;device(e.pointerType==='touch'?'touch':'pointer');touchMain=true;syncMain();});
function mainUp(e,cancel=false){if(e.pointerId!==mainPointer)return;mainPointer=null;touchMain=false;syncMain();if(cancel)pause('触摸操作被取消',true);}
main.addEventListener('pointerup',e=>mainUp(e));main.addEventListener('pointercancel',e=>mainUp(e,true));main.addEventListener('lostpointercapture',e=>mainUp(e,true));
const joy=$('#joystick');joy.addEventListener('pointerdown',e=>{if(menu||stick.id!==null)return;e.preventDefault();focusGame();joy.setPointerCapture(e.pointerId);stick.id=e.pointerId;device('touch');moveStick(e);});
function moveStick(e){if(e.pointerId!==stick.id)return;const r=joy.getBoundingClientRect(),dx=e.clientX-r.x-r.width/2,dy=e.clientY-r.y-r.height/2,rad=r.width*.34,l=Math.hypot(dx,dy),m=Math.min(1,l/rad);stick.x=l?dx/l*m:0;stick.y=l?dy/l*m:0;joy.querySelector('.stick').style.transform=`translate(${stick.x*rad*.7}px,${stick.y*rad*.7}px)`;}
joy.addEventListener('pointermove',moveStick);function endStick(e,cancel=false){if(e.pointerId!==stick.id)return;stick={x:0,y:0,id:null};joy.querySelector('.stick').style.transform='';if(cancel)pause('移动触摸被取消',true);}
joy.addEventListener('pointerup',e=>endStick(e));joy.addEventListener('pointercancel',e=>endStick(e,true));
const precise=$('#precision');precise.addEventListener('pointerdown',e=>{if(menu)return;e.preventDefault();focusGame();precise.setPointerCapture(e.pointerId);precisionPointer=e.pointerId;touchPrecision=true;});for(const type of ['pointerup','pointercancel'])precise.addEventListener(type,e=>{if(e.pointerId===precisionPointer){touchPrecision=false;precisionPointer=null;}});
window.addEventListener('keydown',e=>{
 const inGame=game.contains(document.activeElement);if(!inGame)return;
 if(bindWaiting){e.preventDefault();if(e.code==='Escape'){bindWaiting=null;$('#settingNote').textContent='已取消。';return;}if(e.repeat)return;if(['Tab','Enter'].includes(e.code)){ $('#settingNote').textContent='请使用其他键，保留菜单操作。';return;}const action=bindWaiting;for(const [k,values] of Object.entries(settings.binds))if(k!==action)settings.binds[k]=values.filter(x=>x!==e.code);if(Object.values(settings.binds).some(x=>!x.length)){settings.binds=structuredClone(defaults.binds);$('#settingNote').textContent='该键冲突且会使动作失去按键，已恢复默认。';bindWaiting=null;return;}settings.binds[action]=[e.code];bindWaiting=null;applySettings();settingsPanelRefresh();return;}
 if(e.code==='Escape'&&!e.repeat){e.preventDefault();if(menu==='settings')closeSettings();else if(menu==='pause')resume();else if(!menu)pause();return;}
 if(menu){if(!e.repeat&&menu==='results'&&['Enter','KeyR'].includes(e.code)){e.preventDefault();begin(false);}return;}
 if(Object.values(settings.binds).some(list=>list.includes(e.code))){e.preventDefault();if(e.repeat&&!keys.has(e.code))return;device('keyboard');keys.add(e.code);syncMain();}
});
window.addEventListener('keyup',e=>{keys.delete(e.code);syncMain();if(game.contains(document.activeElement)&&!menu&&Object.values(settings.binds).some(x=>x.includes(e.code)))e.preventDefault();});
window.addEventListener('blur',()=>{runningFocused=false;pause('窗口失去焦点',true);});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('切换了页面',true);});
document.addEventListener('focusin',e=>{if(!game.contains(e.target)){runningFocused=false;pause('离开游戏阅读',true);}});
window.addEventListener('scroll',()=>{if(window.scrollY>Math.min(70,innerHeight*.12)){runningFocused=false;pause('正在阅读下方说明',true);}}, {passive:true});
window.addEventListener('gamepaddisconnected',e=>{if(usedPad===e.gamepad.index){usedPad=null;padMain=false;padVector={x:0,y:0};pause('手柄已断开；连接后或用键盘明确继续',true);}});
function gamepads(now){if(!navigator.getGamepads)return;const pads=navigator.getGamepads(),p=(usedPad!==null?pads[usedPad]:null)||[...pads].find(x=>x&&x.connected);if(!p)return;
 const any=p.buttons.some(b=>b.pressed)||p.axes.some(a=>Math.abs(a)>.3);if(any&&runningFocused)usedPad=p.index;if(any&&usedPad===p.index)device('gamepad');if(usedPad!==p.index)return;
 const bp=i=>!!p.buttons[i]?.pressed,newPress=i=>bp(i)&&!padPrev[i];
 if(newPress(9)){sound.unlock();if(!menu)pause();else if(menu==='pause')resume();}
 if(menu){padMain=(bp(0)&&!padConfirmHeld)||bp(5);syncMain();const items=[...$('#overlay').querySelectorAll('button:not([hidden]),input,select')].filter(e=>!e.disabled&&e.getBoundingClientRect().height>0);const selected=items[menuIndex],adjust=bp(15)||p.axes[0]>.5?1:bp(14)||p.axes[0]<-.5?-1:0;const nav=bp(13)||p.axes[1]>.5?1:bp(12)||p.axes[1]<-.5?-1:0;if(now-lastMenuNav>230){if(selected?.type==='range'&&adjust){selected.value=String(Math.max(0,Math.min(1,Number(selected.value)+adjust*.05)));selected.dispatchEvent(new Event('input'));lastMenuNav=now;}else if(nav||adjust){menuIndex=(menuIndex+(nav||adjust)+items.length)%items.length;lastMenuNav=now;const el=items[menuIndex],body=$('#panelBody');if(el?.closest('.panel-body')){const a=el.getBoundingClientRect(),b=body.getBoundingClientRect();if(a.top<b.top)body.scrollTop+=a.top-b.top-6;else if(a.bottom>b.bottom)body.scrollTop+=a.bottom-b.bottom+6;}}}items.forEach((el,i)=>el.classList.toggle('gamepad-selected',i===menuIndex));if(newPress(0)&&items[menuIndex]){padConfirmHeld=true;sound.unlock();const el=items[menuIndex];if(el.type==='checkbox'){el.checked=!el.checked;el.dispatchEvent(new Event('change'));}else if(el.type==='range'){el.value=String(Math.min(1,Number(el.value)+.1));el.dispatchEvent(new Event('input'));}else el.click();}if(newPress(1)){if(menu==='settings')closeSettings();else if(menu==='pause')resume();}}
 else if(runningFocused){let x=p.axes[0]||0,y=p.axes[1]||0,l=Math.hypot(x,y);if(l<.18)x=y=0;else{const m=Math.min(1,(l-.18)/.82);x=x/l*m;y=y/l*m;}padVector={x,y};padPrecision=bp(4);if(!bp(0))padConfirmHeld=false;padMain=(bp(0)&&!padConfirmHeld)||bp(5);syncMain();}
 padPrev=p.buttons.map(b=>b.pressed);
}
function frame(now){const dt=now-lastFrame;lastFrame=now;gamepads(now);if(!menu&&runningFocused&&sim.state!=='PAUSED'&&sim.state!=='RESULTS'){
 acc+=dt;frameSamples.push(dt);if(frameSamples.length>2000)frameSamples.shift();let count=0;while(acc>=1000/120&&count<240&&!menu){const i=input();if(sim.pendingRelease)i.release=true;if(record){const prev=record.inputs.at(-1);if(!prev||prev.x!==i.x||prev.y!==i.y||prev.precision!==i.precision||i.press||i.release||prev.press||prev.release)record.inputs.push({tick:sim.tick+1,...i});}const start=performance.now();sim.step(i);stepSamples.push(performance.now()-start);if(stepSamples.length>5000)stepSamples.shift();consume();if(record&&sim.tick%120===0&&sim.state!=='READY'){record.samples.push({tick:sim.tick,clock:sim.clock,pos:{...sim.pos},anchor:sim.anchor?{...sim.anchor}:null,action:sim.action,bullets:sim.bullets.length,frame_ms:dt});if(sim.tick%600===0)save('log',{...record,expandedWaves:sim.waves});}acc-=1000/120;count++;}if(acc>1000){pause('设备暂时跟不上模拟，请明确继续',true);}}
 if(latestBank){const q=Math.min(1,(now-latestBank.time)/180);displayScore=latestBank.from+(latestBank.to-latestBank.from)*q;if(q===1)latestBank=null;}else displayScore=sim.score;
 updateHUD();draw();requestAnimationFrame(frame);
}
// Inspection hooks are available only in explicitly marked local test sessions.
if(new URLSearchParams(location.search).has('test'))window.BXTest={get game(){return sim;},snapshot:()=>sim.snapshot(),begin,pause,resume,input:()=>({rawMain,logicalMain,press,release}),showResults:results,perf:()=>({frameSamples,stepSamples}),settings:()=>settings};
resize();applySettings();welcome();requestAnimationFrame(frame);
})();
