'use strict';
(()=>{
const {Engine,C,v,add,sub,mul,len,normalized,analog,digital,geometry}=Qianliu;
const BUILD='qianliu-html-0.1.0',HASH='b7ec56536989fabc136b160f9ce26db971d9246dc1dc5018d52681ba4f04c0d2';
const $=id=>document.getElementById(id),game=$('game'),canvas=$('field'),ctx=canvas.getContext('2d'),panel=$('panel'),screen=$('screen');
const defaults={hold:true,lowMotion:false,textScale:1,master:.8,sfx:.8,music:.35,skipRetry:false,record:false,keys:{up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',rail:'Space',focus:'ShiftLeft',pause:'Escape',retry:'KeyR'},pad:{rail:0,focus:4,pause:9,retry:0,back:1}};
let storageMessage='',settings=structuredClone(defaults),bests={};
try{const raw=JSON.parse(localStorage.getItem('qianliu1912.settings')||'null');if(raw&&typeof raw==='object'){for(const key of ['hold','lowMotion','skipRetry','record'])if(typeof raw[key]==='boolean')settings[key]=raw[key];for(const key of ['master','sfx','music'])if(Number.isFinite(raw[key]))settings[key]=Math.max(0,Math.min(1,raw[key]));if([1,1.25,1.5].includes(raw.textScale))settings.textScale=raw.textScale;for(const key of Object.keys(defaults.keys))if(typeof raw.keys?.[key]==='string'&&/^(Key[A-Z]|Digit[0-9]|Space|ShiftLeft|ShiftRight|ControlLeft|ControlRight|ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Escape|Enter|Tab|AltLeft)$/.test(raw.keys[key]))settings.keys[key]=raw.keys[key];if(new Set(Object.values(settings.keys)).size!==8)settings.keys=structuredClone(defaults.keys);for(const key of Object.keys(defaults.pad))if(Number.isInteger(raw.pad?.[key])&&raw.pad[key]>=0&&raw.pad[key]<=16)settings.pad[key]=raw.pad[key];}const loadedBests=JSON.parse(localStorage.getItem('qianliu1912.bests')||'{}');if(loadedBests&&typeof loadedBests==='object'&&!Array.isArray(loadedBests)){for(const [key,row]of Object.entries(loadedBests))if(/^0:[0-3]$/.test(key)&&row&&typeof row==='object'&&Number.isFinite(row.score)&&row.score>=0)bests[key]={score:row.score,gates:Number.isInteger(row.gates)&&row.gates>=0?row.gates:0,completed:row.completed===true};}}catch(e){storageMessage='本地记录不可用；游戏仍可正常玩。';}
function save(){try{localStorage.setItem('qianliu1912.settings',JSON.stringify(settings));localStorage.setItem('qianliu1912.bests',JSON.stringify(bests));}catch(e){storageMessage='无法保存设置；本次游戏不受影响。';}}
let engine=new Engine(),activeFocus=false,keys=new Set(),physicalKeys=new Set(),blockedKeys=new Set(),touchDirs=new Set(),touchRail=false,touchFocus=false,pendingPress=false,pendingRelease=false,railRequested=false,settingsOpen=false,bindAction=null,fx=[],visualClock=0,scale=1,debug=false,debugIds=false,debugGeometry=false,perfEnabled=false,sessionWall=0,sessionId='',inputDevice='keyboard',panelMode='',pauseReason='',tutorialDone=false,lastHud=-1,lastPad=[],padConnected=false,gamepadRail=false,gamepadFocus=false,padMove=v(),needNewPad=false,renderTimes=[],stepTimes=[],lastSavedResult=null;
const nickname={up:'向上',down:'向下',left:'向左',right:'向右',rail:'牵线',focus:'精移',pause:'暂停',retry:'重试'};
function keyName(code){return {Space:'空格',ShiftLeft:'左 Shift',ShiftRight:'右 Shift',ControlLeft:'左 Ctrl',Escape:'Esc',Enter:'Enter',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',Tab:'Tab',AltLeft:'左 Alt'}[code]||code.replace(/^Key|^Digit/,'');}
function applySettings(){document.documentElement.style.setProperty('--font-scale',settings.textScale);$('keys').innerHTML=`移动 ${['up','left','down','right'].map(x=>keyName(settings.keys[x])).join(' / ')} 或方向键<br>${keyName(settings.keys.rail)} ${settings.hold?'按住牵线，松开脱手':'点按牵线 / 脱手'} · ${keyName(settings.keys.focus)} 精移`;updateRailLabel();resize();}
function updateRailLabel(){const on=!!engine.current;$('rail').textContent=settings.hold?(on?'松开脱手':'按住牵线'):(on?'点按脱手':'点按牵线');$('rail').classList.toggle('pressed',on);$('focus').classList.toggle('pressed',touchFocus||keys.has(settings.keys.focus)||gamepadFocus);}
class Sound{
 constructor(){this.ctx=null;this.activeNodes=0;this.nodes=new Set();this.lastCapture=-1e9;this.deliveries=[];}
 async enable(){try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.main=this.ctx.createGain();this.main.connect(this.ctx.destination);this.hum=this.ctx.createOscillator();this.hum.type='sine';this.hum.frequency.value=92;this.humGain=this.ctx.createGain();this.humGain.gain.value=0;this.hum.connect(this.humGain).connect(this.main);this.hum.start();}await this.ctx.resume();this.main.gain.value=settings.master;}catch(e){}}
 freeze(){if(this.ctx){this.humGain.gain.value=0;this.ctx.suspend().catch(()=>{});}}
 tone(freq,duration=.07,gain=.1,type='sine',music=false,priority=false){if(!this.ctx||this.ctx.state!=='running'||this.activeNodes>=(priority?24:16))return;const ac=this.ctx,t=ac.currentTime,o=ac.createOscillator(),a=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.8),t+duration);a.gain.setValueAtTime(gain*(music?settings.music:settings.sfx),t);a.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(a).connect(this.main);o.start(t);o.stop(t+duration);this.activeNodes++;this.nodes.add(o);o.onended=()=>{o.disconnect();a.disconnect();this.nodes.delete(o);this.activeNodes--;};}
 reset(){for(const o of this.nodes){try{o.stop();}catch(e){}}this.lastCapture=-1e9;this.deliveries=[];if(this.humGain)this.humGain.gain.value=0;}
 event(e){if(!this.ctx)return;const now=this.ctx.currentTime;this.main.gain.value=settings.master;
 if(e.event==='captured'&&now-this.lastCapture>=.1){this.lastCapture=now;this.tone(540,.05,.075,'triangle');}
 if(e.event==='launched')this.tone(220,.04,.025,'sine');
 if(e.event==='delivered'){this.deliveries=this.deliveries.filter(t=>now-t<1);if(this.deliveries.length<12){this.deliveries.push(now);this.tone(880,.07,.065);}}
 if(e.event==='gate_completed')for(const f of [440,554,660])this.tone(f,.18,.06);
 if(['damage','would_hit'].includes(e.event))this.tone(85,.18,.22,'triangle',false,true);
 if(e.event==='needle_warning'){this.tone(1200,.15,.13,'triangle',false,true);this.tone(600,.12,.1,'sine',false,true);}
 if(e.event==='session_end'&&e.reason==='death')for(const f of [230,172,115])this.tone(f,.3,.08,'triangle');
 }
 update(){if(this.ctx?.state==='running'){const bound=engine.objects.filter(b=>b.alive&&b.state==='BOUND').length;this.humGain.gain.setTargetAtTime(Math.min(bound,12)/12*.025*settings.sfx,this.ctx.currentTime,.025);if(engine.tick>0&&engine.tick%240===0)this.tone([110,138.59,164.81,123.47][Math.floor(engine.tick/240)%4],.8,.025,'sine',true);}}
}
const sound=new Sound();
function attach(){engine.onEvent=e=>{sound.event(e);if(['captured','delivered','gate_completed','damage','would_hit','launched'].includes(e.event)){let p=e.position?v(...e.position):e.event==='delivered'||e.event==='gate_completed'?engine.gate().p:engine.objects.find(b=>b.uid===e.uid)?.pos||engine.p;fx.push({event:e.event,p:{...p},until:visualClock+(e.event==='captured'?.05:e.event==='gate_completed'?.18:.25)});}if(engine.recording){Object.assign(e,{session_id:sessionId,participant_code:'local-anonymous',build_id:BUILD,engine_version:'HTML-120Hz',config_hash:HASH,scenario_id:0,transform_id:engine.transformId,input_device:inputDevice,wall_time_ms:Math.round(performance.now()-sessionWall)});}if(e.event==='delivered'&&engine.totalDelivered===1)$('status').textContent='送达了！圆珠真正进了白口。继续接流，注意身体。';};}
attach();
function clearInputs(block=true){if(block)for(const key of physicalKeys)blockedKeys.add(key);keys.clear();touchDirs.clear();touchRail=false;touchFocus=false;pendingPress=false;pendingRelease=false;gamepadRail=false;gamepadFocus=false;padMove=v();needNewPad=true;}
function focusGame(){activeFocus=true;game.focus({preventScroll:true});}
function setPanel(mode,html){panelMode=mode;screen.hidden=!html;panel.innerHTML=html||'';}
function menu(){$('controls').classList.remove('during-result');$('resultControls').hidden=true;$('status').textContent='圆珠能接住；出管后仍危险。白框是当前入口。';clearInputs();engine.mode='MENU';railRequested=false;engine.release();sound.freeze();fx=[];lastSavedResult=null;$('skip').hidden=true;$('pause').hidden=true;$('menuSettings').hidden=false;setPanel('menu',`<h1>牵流</h1><p>150秒内送满至少5个入口，并保住生命。<br>先${settings.hold?'按住':'点按'}牵线留锚，再移动身体拉轨接圆珠。</p><div class="buttons"><button class="primary" data-action="start">开始 · 跟着练</button><button data-action="challenge">直接挑战</button><button data-action="mirror">选择镜像</button></div><div class="minor">圆珠沿锚点 → 身体运输；出管后仍会伤人。</div>`);hud(true);}
function start(tutorial=false,retry=false,transformId=engine.transformId){$('controls').classList.remove('during-result');$('resultControls').hidden=true;sound.reset();clearInputs();railRequested=false;fx=[];visualClock=0;lastSavedResult=null;sessionWall=performance.now();sessionId=crypto.randomUUID?crypto.randomUUID():'local-'+Date.now();engine.recording=settings.record;engine.start(tutorial,transformId,tutorial?0:retry?(settings.skipRetry?0:36):240);engine.debugInvalid=debug;attach();if(engine.recording)Object.assign(engine.log[0],{session_id:sessionId,participant_code:'local-anonymous',build_id:BUILD,engine_version:'HTML-120Hz',config_hash:HASH,scenario_id:0,transform_id:transformId,input_device:inputDevice,wall_time_ms:0});setPanel('',null);$('skip').hidden=!tutorial;$('pause').hidden=false;$('menuSettings').hidden=true;focusGame();sound.enable();hud(true);}
function pause(reason='manual'){if(!['RUNNING','TUTORIAL','COUNTDOWN'].includes(engine.mode))return;engine.pause(reason);pauseReason=reason;clearInputs(false);sound.freeze();const text={reading:'阅读说明时已暂停，回到游戏后再继续。',blur:'离开窗口时已暂停。',resize:'画面尺寸改变，已暂停。',gamepad:'手柄断开，已暂停。'}[reason]||'计时、弹珠和旧轨排空都已冻结。';setPanel('pause',`<h2>已暂停</h2><p>${text}</p><div class="buttons"><button class="primary" data-action="resume">继续游戏</button><button data-action="settings">设置</button><button data-action="menu">返回菜单</button></div>`);hud(true);}
function resume(){if(engine.invalid)return;settingsOpen=false;$('settingsScreen').hidden=true;const actualPad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);const actuallyHeld=physicalKeys.has(settings.keys.rail)||touchRail||!!actualPad?.buttons[settings.pad.rail]?.pressed;clearInputs(false);railRequested=!!engine.current;if(settings.hold&&engine.current&&!actuallyHeld){pendingRelease=true;railRequested=false;}engine.resume();setPanel('',null);focusGame();sound.enable();hud(true);}
function showResult(){if(panelMode==='result'||panelMode==='trace')return;$('controls').classList.add('during-result');$('resultControls').hidden=false;$('traceButton').hidden=engine.result.reason!=='death';$('traceButton').textContent='查看致伤轨迹';$('status').textContent='本轮结束。重玩保留同一局面，也可以换镜像或返回。';clearInputs();if(sound.humGain)sound.humGain.gain.value=0;railRequested=false;$('skip').hidden=true;const r=engine.result,key='0:'+engine.transformId,previous=lastSavedResult?.previous??(Number(bests[key]?.score)||0),diff=r.score-previous;if(!lastSavedResult&&!engine.tutorial&&!debug&&!engine.debugInvalid&&!engine.invalid){if(r.score>=previous)bests[key]={score:r.score,gates:r.gateCount,completed:r.reason==='success'};save();}lastSavedResult={previous,diff};const title=r.reason==='death'?'生命耗尽，本轮中断':r.reason==='success'?'完成挑战':'时间到，送达不足';const why=r.reason==='death'?engine.deathObject?.kind==='needle'?'被穿线针击中。它会穿线，身体要躲开。':'被自由圆珠击中。出管后的圆珠仍危险。':r.reason==='success'?'150秒结束时仍然存活，并已送满至少5口。':`存活到150秒，但只送满${r.gateCount}口；需要至少5口。`;setPanel('result',`<h2>${title}</h2><p>${why}</p><div class="result-grid"><span>送达<b>${r.totalDelivered}颗</b></span><span>填满<b>${r.gateCount}口</b></span><span>分数<b>${r.score}</b></span><span>存活<b>${(r.survivalTicks/120).toFixed(1)}秒</b></span><span>生命<b>${r.hp}</b></span><span>同局最佳差<b>${diff>=0?'+':''}${diff}</b></span></div>${debug||engine.debugInvalid?'<div class="notice">调试局，不保存正式成绩</div>':''}`);hud(true);}
function mirrorMenu(){settingsOpen=true;$('settingsScreen').hidden=false;$('settingsTitle').textContent='选择镜像场景';$('closeSettings').textContent='返回';$('settingsBody').innerHTML=`<p class="notice">重玩会保留当前镜像。这里选择后才会换局。</p><div class="buttons">${['原样','左右镜像','上下镜像','双镜像'].map((name,id)=>`<button data-transform="${id}" class="${id===engine.transformId?'primary':''}">${name}${id===engine.transformId?' · 当前':''}</button>`).join(' ')}</div>`;}
function settingsMenu(){if(['RUNNING','TUTORIAL','COUNTDOWN'].includes(engine.mode))pause();settingsOpen=true;bindAction=null;$('settingsScreen').hidden=false;$('settingsTitle').textContent='设置';$('closeSettings').textContent=engine.mode==='MENU'?'返回菜单':'返回游戏';
 $('settingsBody').innerHTML=`<div class="setting-row"><label for="holdSetting">牵线操作</label><select id="holdSetting"><option value="hold" ${settings.hold?'selected':''}>按住，松开脱手</option><option value="toggle" ${!settings.hold?'selected':''}>点按牵线 / 脱手</option></select></div><div class="setting-row"><label for="motionSetting">减少运动效果</label><input type="checkbox" id="motionSetting" ${settings.lowMotion?'checked':''}></div><div class="setting-row"><label for="textSetting">文字大小</label><select id="textSetting">${[1,1.25,1.5].map(s=>`<option value="${s}" ${s===settings.textScale?'selected':''}>${s*100}%</option>`).join('')}</select></div>${[['master','主音量'],['sfx','效果音量'],['music','音乐音量']].map(([key,label])=>`<div class="setting-row"><label for="${key}Setting">${label}</label><input type="range" id="${key}Setting" data-volume="${key}" min="0" max="1" step=".05" value="${settings[key]}"></div>`).join('')}<div class="setting-row"><label for="retrySetting">重试时跳过短倒数</label><input type="checkbox" id="retrySetting" ${settings.skipRetry?'checked':''}></div><div class="setting-heading">键盘操作 · 点一项后按新键</div><div class="key-grid">${Object.keys(nickname).map(k=>`<button data-bind="${k}"><span>${nickname[k]}</span><b>${keyName(settings.keys[k])}</b></button>`).join('')}</div><p class="notice" id="bindNotice">方向键始终可移动。返回保留 Esc，结果重试保留 Enter。</p><button data-action="resetKeys">恢复默认操作</button><div class="setting-heading">手柄动作按钮</div>${[['rail','牵线'],['focus','精移'],['pause','暂停'],['retry','结果重试'],['back','结果返回']].map(([key,label])=>`<div class="setting-row"><label>${label}</label><select data-pad-bind="${key}">${Array.from({length:17},(_,id)=>`<option value="${id}" ${id===settings.pad[key]?'selected':''}>${['A / 底部','B / 右侧','X / 左侧','Y / 顶部','LB','RB','LT','RT','Back','Start','L3','R3','上','下','左','右','Home'][id]}</option>`).join('')}</select></div>`).join('')}<p class="notice" id="padNotice">摇杆与十字键移动；需浏览器能读到手柄。实体手柄未在本机验收。</p><div class="setting-heading">本地试玩记录</div><div class="setting-row"><label for="recordSetting">下一局记录游戏内输入与事件</label><input type="checkbox" id="recordSetting" ${settings.record?'checked':''}></div><p class="notice">默认关闭。只记录匿名游戏动作，不记录其他键盘输入。保存在当前页面内，由你导出；不会上传。修改记录开关下一局生效。</p><button data-action="export">导出本局记录</button><div class="setting-heading">调试 · 使用后不保存正式成绩</div><div class="buttons"><button data-action="debug">${debug?'关闭':'开启'}判定核与状态</button><button data-action="step">暂停单步</button><button data-action="performance">${perfEnabled?'停止':'开启'}性能采样</button></div><p class="notice" id="debugNotice">${storageMessage||'无敌环是短暂保护；真实命中核始终可见。'}</p>`;}
function exportRecord(){const common={session_id:sessionId,participant_code:'local-anonymous',build_id:BUILD,engine_version:'HTML-120Hz',config_hash:HASH,scenario_id:0,transform_id:engine.transformId,input_device:inputDevice};const rows=[{event:'export_metadata',...common,sim_tick:engine.tick,wall_time_ms:Math.round(performance.now()-sessionWall),recording_enabled:engine.recording,settings:{hold:settings.hold,keys:settings.keys,pad:settings.pad},config:C},...engine.log,...engine.inputLog.map(i=>({event:'input_sample',...common,sim_tick:i.tick,wall_time_ms:i.wall_time_ms??null,input_device:i.input_device||inputDevice,input:i})),{event:'performance_sample',...common,sim_tick:engine.tick,wall_time_ms:Math.round(performance.now()-sessionWall),units:'ms',render:pstats(renderTimes),physics:pstats(stepTimes)}];const a=document.createElement('a'),url=URL.createObjectURL(new Blob([rows.map(x=>JSON.stringify(x)).join('\n')],{type:'application/x-ndjson'}));a.href=url;a.download='qianliu1912-'+(sessionId||'local')+'.jsonl';a.click();URL.revokeObjectURL(url);$('debugNotice').textContent=engine.recording?'已导出本局记录。':'本局未开启详细记录，导出仅包含配置与当前结果；没有伪造输入。';}
function pstats(a){if(!a.length)return null;const sorted=[...a].sort((x,y)=>x-y);return {n:a.length,p95:sorted[Math.floor(a.length*.95)],p99:sorted[Math.floor(a.length*.99)],max:sorted.at(-1)};}
function action(name){sound.enable();if(name==='trace'){if(panelMode==='trace'){panelMode='';showResult();}else{setPanel('trace',null);$('traceButton').textContent='返回结算';$('status').textContent='红线：致伤物最后0.25秒的真实轨迹；红圈：击中位置。';}return;}if(name==='start')start(true);if(name==='challenge')start(false);if(name==='practice')start(true);if(name==='retry'){engine.emit('retry_selected',{target_transform_id:engine.transformId,real_choice_available:true});start(false,true);}if(name==='resume')resume();if(name==='menu'){engine.emit('exit_selected',{real_choice_available:true});menu();}if(name==='settings')settingsMenu();if(name==='mirror')mirrorMenu();if(name==='resetKeys'){settings.keys=structuredClone(defaults.keys);settings.pad=structuredClone(defaults.pad);save();applySettings();settingsMenu();}if(name==='export')exportRecord();if(name==='debug'){debug=!debug;engine.debugInvalid=true;settingsMenu();}if(name==='step'&&engine.mode==='PAUSED'){debug=true;const mode=engine.previousMode;engine.mode=mode;engine.step({});if(engine.mode!== 'RESULTS')engine.mode='PAUSED';hud(true);}if(name==='performance'){perfEnabled=!perfEnabled;engine.debugInvalid=true;settingsMenu();}}
game.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(button){action(button.dataset.action);return;}const b=e.target.closest('[data-bind]');if(b){bindAction=b.dataset.bind;$('bindNotice').textContent=`为「${nickname[bindAction]}」按一个新键。Esc 取消。`;return;}const t=e.target.closest('[data-transform]');if(t){settingsOpen=false;$('settingsScreen').hidden=true;start(false,false,Number(t.dataset.transform));}});
$('closeSettings').onclick=()=>{bindAction=null;settingsOpen=false;$('settingsScreen').hidden=true;applySettings();if(engine.mode==='MENU')menu();else hud(true);focusGame();};
$('settingsBody').addEventListener('change',e=>{const el=e.target;if(el.id==='holdSetting'){const hold=el.value==='hold';if(hold!==settings.hold){engine.release();settings.hold=hold;railRequested=false;clearInputs();}}
 if(el.id==='motionSetting')settings.lowMotion=el.checked;if(el.id==='textSetting')settings.textScale=Number(el.value);if(el.id==='retrySetting')settings.skipRetry=el.checked;if(el.id==='recordSetting')settings.record=el.checked;if(el.dataset.volume)settings[el.dataset.volume]=Number(el.value);
 if(el.dataset.padBind){const key=el.dataset.padBind,val=Number(el.value),group=['rail','focus','pause'].includes(key)?['rail','focus','pause']:['retry','back'];const conflict=group.find(k=>k!==key&&settings.pad[k]===val);if(conflict){$('padNotice').textContent=`冲突：该按钮已用于「${{rail:'牵线',focus:'精移',pause:'暂停',retry:'结果重试',back:'结果返回'}[conflict]}」。`;el.value=settings.pad[key];}else settings.pad[key]=val;}save();applySettings();});
$('menuSettings').onclick=()=>{focusGame();settingsMenu();};$('pause').onclick=()=>{focusGame();if(engine.mode==='PAUSED')resume();else pause();};$('skip').onclick=()=>start(false);
function battle(){return activeFocus&&!settingsOpen&&['RUNNING','TUTORIAL'].includes(engine.mode);}
function railDown(){if(!battle())return;if(settings.hold){if(!railRequested){railRequested=true;pendingPress=true;}}else{railRequested=!railRequested;if(railRequested)pendingPress=true;else pendingRelease=true;}}
function railUp(){if(settings.hold&&railRequested){railRequested=false;pendingRelease=true;}}
function relevant(code){return Object.values(settings.keys).includes(code)||(code==='ShiftRight'&&settings.keys.focus==='ShiftLeft'&&!Object.values(settings.keys).includes('ShiftRight'))||['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','Escape','F1','F2','F3','F4','F5','F6','F7','F8','F9'].includes(code);}
window.addEventListener('keydown',e=>{
 if(!activeFocus||!game.contains(document.activeElement)||!relevant(e.code)&&!bindAction)return;
 if(settingsOpen){if(bindAction){e.preventDefault();if(e.code==='Escape'){bindAction=null;$('bindNotice').textContent='已取消改键。';return;}if(e.repeat)return;const other=Object.keys(settings.keys).find(k=>k!==bindAction&&settings.keys[k]===e.code);const reserved=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','Escape'].includes(e.code)&&e.code!==defaults.keys[bindAction];if(other||reserved){$('bindNotice').textContent=`冲突：${keyName(e.code)}${other?'已用于「'+nickname[other]+'」':'是保留操作'}，请换一个键。`;return;}if(!/^(Key[A-Z]|Digit[0-9]|Space|ShiftLeft|ShiftRight|ControlLeft|ControlRight|Escape|Tab|AltLeft)$/.test(e.code)){$('bindNotice').textContent='请选择字母、数字、空格或修饰键。';return;}settings.keys[bindAction]=e.code;bindAction=null;save();applySettings();settingsMenu();}return;}
 e.preventDefault();physicalKeys.add(e.code);if(e.repeat||blockedKeys.has(e.code))return;keys.add(e.code);inputDevice='keyboard';sound.enable();
 if(e.code===settings.keys.pause||e.code==='Escape'){if(engine.mode==='RESULTS')menu();else if(engine.mode==='PAUSED')resume();else pause();return;}
 if(engine.mode==='RESULTS'&&(e.code===settings.keys.retry||e.code==='Enter')){action('retry');return;}
 if(engine.mode==='MENU'&&e.code==='Enter'){start(true);return;}
 if(battle()&&e.code===settings.keys.rail)railDown();
 if(e.code.startsWith('F')){const n=Number(e.code.slice(1));if(n===1){debug=!debug;engine.debugInvalid=true;}if(n===2){debugIds=!debugIds;debug=true;}if(n===3){debugGeometry=!debugGeometry;debug=true;}if(n===4){debug=true;}if(n===5){if(engine.mode!=='PAUSED')pause();else action('step');}if(n===6){debug=true;start(false,true);}if(n===7){debug=true;engine.debugInvalid=true;engine.invulnerableUntil=engine.tick+18000;}if(n===8)perfEnabled=!perfEnabled;if(n===9){settingsMenu();exportRecord();}}
});
window.addEventListener('keyup',e=>{keys.delete(e.code);physicalKeys.delete(e.code);blockedKeys.delete(e.code);if(e.code===settings.keys.rail){if(battle())railUp();else railRequested=false;}});
function pointerControl(el,down,up){el.addEventListener('pointerdown',e=>{e.preventDefault();focusGame();if(!battle())return;sound.enable();inputDevice='touch';el.setPointerCapture(e.pointerId);el.classList.add('pressed');down(e);});const end=e=>{el.classList.remove('pressed');up(e);};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end);}
for(const b of document.querySelectorAll('[data-dir]'))pointerControl(b,()=>touchDirs.add(b.dataset.dir),()=>touchDirs.delete(b.dataset.dir));
pointerControl($('rail'),()=>{touchRail=true;railDown();},()=>{touchRail=false;if(battle())railUp();});pointerControl($('focus'),()=>touchFocus=true,()=>touchFocus=false);
canvas.addEventListener('pointerdown',()=>{focusGame();sound.enable();});
game.addEventListener('focusin',()=>activeFocus=true);game.addEventListener('focusout',e=>{if(game.contains(e.relatedTarget))return;setTimeout(()=>{if(!game.contains(document.activeElement)){activeFocus=false;pause('reading');}},0);});
window.addEventListener('blur',()=>{physicalKeys.clear();activeFocus=false;pause('blur');});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('blur');});window.addEventListener('scroll',()=>{if(window.scrollY>20){activeFocus=false;pause('reading');clearInputs(false);}}, {passive:true});
function pollPad(){const pads=navigator.getGamepads?.()||[],pad=Array.from(pads).find(Boolean);if(!pad){if(padConnected)pause('gamepad');padConnected=false;lastPad=[];gamepadRail=false;gamepadFocus=false;padMove=v();return;}padConnected=true;const pressed=pad.buttons.map(b=>b.pressed);if(needNewPad){if(pressed.every(x=>!x))needNewPad=false;lastPad=pressed;padMove=v();return;}const edge=n=>pressed[n]&&!lastPad[n],buttons=settings.pad;if(activeFocus&&!settingsOpen){if(edge(buttons.pause)){if(engine.mode==='PAUSED')resume();else pause();}else if(engine.mode==='RESULTS'){if(edge(buttons.retry))action('retry');if(edge(buttons.back))menu();}else if(engine.mode==='MENU'&&edge(buttons.rail))start(true);else if(battle()){const a=analog(pad.axes[0]||0,pad.axes[1]||0),d=digital((pressed[15]?1:0)-(pressed[14]?1:0),(pressed[13]?1:0)-(pressed[12]?1:0));padMove=len(d)?d:a;gamepadFocus=!!pressed[buttons.focus];gamepadRail=!!pressed[buttons.rail];if(edge(buttons.rail)){inputDevice='gamepad';railDown();}if(!pressed[buttons.rail]&&lastPad[buttons.rail])railUp();}}lastPad=pressed;}
function input(){let x=(keys.has(settings.keys.right)||keys.has('ArrowRight')?1:0)-(keys.has(settings.keys.left)||keys.has('ArrowLeft')?1:0)+(touchDirs.has('right')?1:0)-(touchDirs.has('left')?1:0),y=(keys.has(settings.keys.down)||keys.has('ArrowDown')?1:0)-(keys.has(settings.keys.up)||keys.has('ArrowUp')?1:0)+(touchDirs.has('down')?1:0)-(touchDirs.has('up')?1:0);let d=len(v(x,y))?digital(x,y):padMove;const out={x:d.x,y:d.y,focus:touchFocus||keys.has(settings.keys.focus)||keys.has('ShiftRight')&&settings.keys.focus==='ShiftLeft'&&!Object.values(settings.keys).includes('ShiftRight')||gamepadFocus,press:pendingPress,release:pendingRelease};pendingPress=false;pendingRelease=false;return out;}
function hud(force=false){if(!force&&lastHud===Math.floor(engine.tick/12))return;lastHud=Math.floor(engine.tick/12);const e=engine,teach=e.tutorial&&e.mode!=='MENU';$('hp').textContent=teach?'练习免扣生命':`生命 ${e.hp}`;$('time').textContent=teach?`教学 ${e.tutorialStep}`:`剩余 ${Math.max(0,Math.ceil((18000-e.tick)/120))}秒`;$('score').textContent=teach?`送达 ${e.totalDelivered}`:`分数 ${e.score}`;$('progress').textContent=teach&&e.tutorialStep==='C'?(e.needleSeen?'针已通过':'移动躲针'):`当前口 ${e.delivered} / ${teach?6:20}`;$('modeLabel').textContent=e.mode==='MENU'?'入门与挑战':teach?'入门练习':['原样','左右镜像','上下镜像','双镜像'][e.transformId];
 const key=keyName(settings.keys.rail),hold=settings.hold?`按住${key}或「牵线」`:`点按${key}或「牵线」`,release=settings.hold?'松开牵线':'点按脱手';let hint;
 if(teach){$('target').textContent=e.tutorialStep==='A'?'练习A：向右口送6颗圆珠':e.tutorialStep==='B'?'练习B：脱手换轨，向左口送6颗':'练习C：尖针穿线，移动身体躲开';hint=e.tutorialStep==='A'?`${hold}留锚，再向右走到虚线影子。圆珠会沿轨从身体前方射向右口。`:e.tutorialStep==='B'?`${release}，先到右边再向左拉轨。左口需6颗，还需一次有效轨后的脱手。`:'红白尖针会穿过导轨。双虚线锁住的是预告开始时的位置，移动身体离开它。';if(e.tutorialStep==='B'&&e.delivered>=6&&!e.releaseB)hint=`左口已满；还需${release}一次。有效轨即使没有圆珠也可以脱手。`;if(e.hintShown)hint=e.tutorialStep==='A'?`${hold}，从影子左边向右拉；让出口箭头水平朝白口。`:e.tutorialStep==='B'?`${release}后去右侧留锚，向左拉过顶部圆珠来流。`:'看到双虚线后横向移开；本练习不扣生命。';}
 else{$('target').textContent=`目标：存活150秒 · 填满 ${e.gateCount} / 至少5口`;hint=e.current?.state==='FORMING'?`还差 ${Math.max(0,Math.ceil(64-e.current.L))} 才能接珠。继续移动拉开；箭头将从锚点指向身体。`:e.current?.state==='ACTIVE'?`${release}可换位；虚线旧轨仍会排空。出管圆珠也会伤人，身体附近断开段不保护你。`:`${hold}留锚，再移动拉出实线；把出口箭头朝向白色入口，接住来流。`;}
 if(e.mode==='MENU')hint=`先${settings.hold?'按住':'点按'}「牵线」留锚，再向右移动拉出导轨。接住的圆珠会从身体前方射出。`;if(e.mode==='COUNTDOWN')hint=`${Math.ceil(e.countdown/120)}秒后开始。圆珠有危险；接过的圆珠真正进入白口才算送达。`;$('hint').textContent=hint;updateRailLabel();$('pause').textContent=e.mode==='PAUSED'?'继续':'暂停';
 if(teach&&e.tutorialStep==='C'&&e.needleSeen&&panelMode!=='tutorialReady')setPanel('tutorialReady','<h2>练习完成</h2><p>尖针穿线；身体要离开预告路径。<br>挑战要在150秒结束时存活，并送满至少5口。</p><div class="buttons"><button class="primary" data-action="challenge">开始挑战</button><button data-action="practice">再练一次</button><button data-action="menu">返回菜单</button></div>');
 if(e.invalid&&panelMode!=='invalid'){sound.freeze();setPanel('invalid',`<h2>本局已暂停</h2><p>检测到模拟故障：${e.invalid}<br>本局不保存成绩，请重新开始。</p><div class="buttons"><button class="primary" data-action="retry">重新开始</button><button data-action="settings">查看 / 导出记录</button><button data-action="menu">返回菜单</button></div>`);}
}
function resize(){const h=window.visualViewport?.height||innerHeight;document.documentElement.style.setProperty('--game-height',Math.floor(h)+'px');const box=$('stage').getBoundingClientRect(),w=Math.max(1,Math.min(box.width-4,(box.height-4)*1280/720)),hh=w*720/1280;canvas.style.width=w+'px';canvas.style.height=hh+'px';scale=w/1280;const dpr=Math.max(1,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(hh*dpr);ctx.setTransform(canvas.width/1280,0,0,canvas.height/720,0,0);}
let previousSize=[innerWidth,innerHeight];window.addEventListener('resize',()=>{const now=[innerWidth,innerHeight];if(Math.abs(now[0]-previousSize[0])>30||Math.abs(now[1]-previousSize[1])>60)pause('resize');previousSize=now;resize();});window.visualViewport?.addEventListener('resize',resize);new ResizeObserver(resize).observe($('stage'));
const colors={mint:'#bdefe8',amber:'#ffc06a',needle:'#ff6b73',white:'#f7f4ec'};
function line(a,b,color,width=1,dash=[]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}
function circle(p,r,color,width=1,fill=false){ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.lineWidth=width;ctx.strokeStyle=color;ctx.fillStyle=color;fill?ctx.fill():ctx.stroke();}
function text(str,p,color,size=20,align='center'){ctx.fillStyle=color;ctx.font=`600 ${Math.max(size,11/Math.max(scale,.05))*settings.textScale}px -apple-system, "PingFang SC", sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(str,p.x,p.y);}
function drawGate(gate,next=false){const {p,side}=gate,vertical=side==='left'||side==='right',offset=vertical?v(0,80):v(80,0);line(sub(p,offset),add(p,offset),next?'#66818b':colors.white,next?2:8,next?[8,8]:[]);const inside=side==='right'?v(-18,0):side==='left'?v(18,0):side==='top'?v(0,18):v(0,-18);if(next){const label=add(p,mul(inside,3.5));text('下一口',label,'#8da4ad',18,side==='left'?'left':side==='right'?'right':'center');}else{const marker=add(p,mul(inside,3.3));text(engine.gateState==='DRAINING'?'已满 · 换口':`${engine.delivered}/${engine.tutorial?6:20}`,marker,colors.white,23,side==='left'?'left':side==='right'?'right':'center');const total=engine.tutorial?6:20;for(let i=0;i<total;i++){const a=add(sub(p,offset),mul(offset,2*(i+.18)/total)),b=add(sub(p,offset),mul(offset,2*(i+.82)/total));line(add(a,inside),add(b,inside),i<engine.delivered?colors.mint:'#43535d',4);}}
}
function draw(){const e=engine;ctx.clearRect(0,0,1280,720);ctx.fillStyle='#111820';ctx.fillRect(0,0,1280,720);ctx.strokeStyle='#1d2b35';ctx.lineWidth=1;for(let x=90;x<=1190;x+=50)line(v(x,60),v(x,660),'#1d2b35');for(let y=60;y<=660;y+=50)line(v(90,y),v(1190,y),'#1d2b35');ctx.strokeStyle='#526670';ctx.lineWidth=2;ctx.strokeRect(90,60,1100,600);
 for(const w of e.warnings){if(w.type==='N'){const dir=normalized(sub(w.target,w.pos)),perp=v(-dir.y*5,dir.x*5);line(add(w.pos,perp),add(w.target,perp),'#ff6b7370',2,[9,9]);line(sub(w.pos,perp),sub(w.target,perp),'#f7f4ec80',2,[9,9]);circle(w.target,16,'#ff6b73',2);text('尖针预告',add(w.pos,v(0,35)),colors.needle,18);}else{circle(w.pos,14,'#ffc06a',2);}}
 for(const f of fx){if(f.until<=visualClock)continue;const remaining=f.until-visualClock;circle(f.p,settings.lowMotion?12:8+(1-remaining/.25)*23,f.event==='damage'||f.event==='would_hit'?colors.needle:colors.mint,2);}
 for(const r of e.rails.values()){
 if(r.state==='DRAINING'){line(r.a,r.p,'#bdefe860',2,[7,9]);circle(add(r.p,mul(r.d,12)),6,'#a6c7c0',1);}
 else if(r.state==='FORMING'){line(r.a,r.p,'#76949f',2,[4,6]);circle(r.a,7,'#bdefe8',2);}
 else{const a=add(r.a,mul(r.d,16)),b=add(r.p,mul(r.d,-24));line(a,b,'#bdefe824',12);line(a,b,colors.mint,4);line(r.a,a,'#78928f',1,[2,3]);line(b,r.p,'#78928f',1,[2,4]);circle(r.a,7,colors.mint,2);const outlet=add(r.p,mul(r.d,12)),tip=add(outlet,mul(r.d,64));line(outlet,tip,colors.mint,2);const n=v(-r.d.y,r.d.x);line(tip,add(sub(tip,mul(r.d,12)),mul(n,5)),colors.mint,2);line(tip,sub(sub(tip,mul(r.d,12)),mul(n,5)),colors.mint,2);circle(outlet,5,colors.mint,1);
 const wall=Qianliu.wallSweep(outlet,add(outlet,mul(r.d,2000)));if(wall)circle(add(outlet,mul(r.d,2000*wall.t)),9,'#789c9f',2);
 if(r.L>=270){ctx.beginPath();ctx.arc(r.a.x,r.a.y,300,0,Math.PI*2);ctx.strokeStyle='#bdefe817';ctx.lineWidth=2;ctx.stroke();}if(debug){line(a,b,'#e374bb',16);text(`L ${r.L.toFixed(1)}`,add(r.a,v(0,-22)),colors.mint,14);}}
 }
 if(e.tutorial&&e.tutorialStep==='A'){circle(v(580,360),16,'#bdefe870',2);line(v(445,360),v(556,360),'#bdefe850',2,[5,8]);if(e.sourceStart===null)text('向右拉到影子',v(580,315),'#bdefe8',20);}
 for(const b of e.objects){if(!b.alive)continue;if(b.state==='BOUND'){circle(b.pos,4,colors.mint,1,true);const r=e.rails.get(b.railId);if(r){const n=v(-r.d.y,r.d.x);line(add(b.pos,mul(n,-7)),add(b.pos,mul(n,7)),colors.mint,2);}}else if(b.kind==='bead'){circle(b.pos,Math.max(4,2/scale),colors.amber,Math.max(1.2,1/scale));circle(b.pos,2,colors.amber,1,true);if(b.routed){line(add(b.pos,v(4,-3)),add(b.pos,v(4,0)),colors.white,2);}}else{const d=normalized(b.velocity),n=v(-d.y,d.x);ctx.beginPath();ctx.moveTo(b.pos.x+d.x*9,b.pos.y+d.y*9);ctx.lineTo(b.pos.x+n.x*4,b.pos.y+n.y*4);ctx.lineTo(b.pos.x-d.x*9,b.pos.y-d.y*9);ctx.lineTo(b.pos.x-n.x*4,b.pos.y-n.y*4);ctx.closePath();ctx.fillStyle=colors.needle;ctx.fill();line(sub(b.pos,mul(d,6)),add(b.pos,mul(d,6)),colors.white,2);}if(debugIds)text(String(b.uid),add(b.pos,v(0,-12)),colors.white,10);}
 let d=e.current?.d||normalized(sub(e.p,e.pPrev));if(!len(d))d=v(1,0);const angle=Math.atan2(d.y,d.x);ctx.beginPath();ctx.arc(e.p.x,e.p.y,13,angle+.34,angle+Math.PI*2-.34);ctx.strokeStyle=colors.mint;ctx.lineWidth=4;ctx.stroke();circle(e.p,6,'#243b41',1,true);circle(e.p,2.5,colors.white,1,true);if(e.tick<e.invulnerableUntil)circle(e.p,21,colors.white,2);if(debug)circle(e.p,6,'#ff6b73',1);
 if(e.mode==='RESULTS'&&e.result.reason==='death'){for(let i=1;i<e.deathHistory.length;i++){const a=e.deathHistory[i-1],b=e.deathHistory[i];line(v(a.x,a.y),v(b.x,b.y),colors.needle,2);}if(e.deathObject)circle(e.deathObject.pos,12,colors.needle,3);}
 if(e.tutorial&&e.tutorialStep==='C'){}else{if(!e.tutorial||e.tutorialStep==='A')drawGate(e.nextGate(),true);drawGate(e.gate());}
 if(debug)text(`tick ${e.tick} · ${e.objects.length}物体 · ${e.rails.size}轨 · ${e.gateState}`,v(110,690),'#b7cfcc',14,'left');
}
let last=performance.now(),accumulator=0;
function frame(now){const elapsed=Math.max(0,(now-last)/1000);last=now;pollPad();if(['RUNNING','TUTORIAL','COUNTDOWN'].includes(engine.mode)&&!settingsOpen){if(elapsed>.5){pause('blur');accumulator=0;}else{accumulator+=elapsed;let steps=0;while(accumulator>=1/120&&steps<60&&['RUNNING','TUTORIAL','COUNTDOWN'].includes(engine.mode)){const begin=performance.now();engine.step(input());if(engine.recording&&engine.inputLog.length){const row=engine.inputLog.at(-1);if(row.wall_time_ms===undefined){row.wall_time_ms=Math.round(performance.now()-sessionWall);row.input_device=inputDevice;}}if(perfEnabled)stepTimes.push(performance.now()-begin);sound.update();accumulator-=1/120;visualClock+=1/120;steps++;}}}else accumulator=0;fx=fx.filter(f=>f.until>visualClock);hud();if(engine.mode==='RESULTS')showResult();const begin=performance.now();draw();if(perfEnabled){renderTimes.push(performance.now()-begin);if(renderTimes.length>20000)renderTimes.shift();if(stepTimes.length>40000)stepTimes.splice(0,120);}requestAnimationFrame(frame);}
// Read-only diagnostics for verification; UI never uses these to complete a run.
window.QianliuDemo={get state(){return engine.snapshot();},get engine(){return engine;},get settings(){return structuredClone(settings);},get diagnostics(){return {activeFocus,settingsOpen,scale,audio:{active_nodes:sound.activeNodes,maximum_nodes:24,hum_bound_count_cap:12},render:pstats(renderTimes),physics:pstats(stepTimes)};}};
applySettings();menu();resize();requestAnimationFrame(frame);
})();
